//=======================================================================================
// ____          ____    __    ______     __________   __      __       __        __         
// \    \       |    |  |  |  |   _   \  |___    ___| |  |    |  |     /  \      |  |        
//  \    \      |    |  |  |  |  |_)   |     |  |     |  |    |  |    /    \     |  |        
//   \    \     |    |  |  |  |   _   /      |  |     |  |    |  |   /  /\  \    |  |        
//    \    \    |    |  |  |  |  | \  \      |  |     |   \__/   |  /  ____  \   |  |____    
//     \    \   |    |  |__|  |__|  \__\     |__|      \________/  /__/    \__\  |_______|   
//      \    \  |    |   ________________________________________________________________    
//       \    \ |    |  |  ______________________________________________________________|   
//        \    \|    |  |  |         __          __     __     __     ______      _______    
//         \         |  |  |_____   |  |        |  |   |  |   |  |   |   _  \    /  _____)   
//          \        |  |   _____|  |  |        |  |   |  |   |  |   |  | \  \   \_______    
//           \       |  |  |        |  |_____   |   \_/   |   |  |   |  |_/  /    _____  \   
//            \ _____|  |__|        |________|   \_______/    |__|   |______/    (_______/   
//
//  This file is part of VirtualFluids. VirtualFluids is free software: you can 
//  redistribute it and/or modify it under the terms of the GNU General Public
//  License as published by the Free Software Foundation, either version 3 of 
//  the License, or (at your option) any later version.
//  
//  VirtualFluids is distributed in the hope that it will be useful, but WITHOUT 
//  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
//  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
//  for more details.
//  
//  You should have received a copy of the GNU General Public License along
//  with VirtualFluids (see COPYING.txt). If not, see <http://www.gnu.org/licenses/>.
//
//! \file buildInfo.cpp
//! \ingroup Core
//! \author Soeren Peters
//
// Generated by CMake!
//
//=======================================================================================
#include "VirtualFluidsDefinitions.h"

namespace buildInfo
{
    VF_PUBLIC const char *gitCommitHash() { return "@git_commit_hash@";  }
    VF_PUBLIC const char *gitBranch()     { return "@git_branch@";       }
    VF_PUBLIC const char *buildType()     { return "@CMAKE_BUILD_TYPE@"; }
    VF_PUBLIC const char *compilerFlags() { return "@COMPILER_FLAGS@";   }
    VF_PUBLIC const char *buildMachine()  { return "@BUILD_computerName@";}
    VF_PUBLIC const char *projectDir()    { return "@CMAKE_SOURCE_DIR@"; }
    VF_PUBLIC const char *binaryDir()     { return "@CMAKE_BINARY_DIR@"; }
}
