#!/bin/bash -l

#SBATCH --partition=gpu01_queue
#SBATCH --nodes=1
#SBATCH --time=03:00:00
#SBATCH --job-name=Regr4GPU
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:4
#SBATCH --output=multigpu_test/slurm4GPU.out
##SBATCH --exclusive

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURM_TASKS_PER_NODE"=$SLURM_TASKS_PER_NODE

module purge
module load comp/gcc/10.2.0
module load mpi/openmpi/4.0.5_gcc_9.3/openmpi
module load cuda/11.3
module load comp/git/2.27.0
PATH=/home/irmb/tools/cmake-3.26.4-linux-x86_64/bin:$PATH

module list

cd multigpu_test
rm -rf build && mkdir -p build
cd build
cmake .. -DVF_ENABLE_GPU=ON -DCMAKE_CUDA_ARCHITECTURES=60 -DUSER_APPS=apps/gpu/DrivenCavityMultiGPU\;apps/gpu/SphereMultiGPU
make -j 16
cd ..
mkdir -p output

echo $'\n\n\n\n---First test: DrivenCavityMultiGPU on 4 GPUs\n\n'
mpirun -np 4 "./build/bin/DrivenCavityMultiGPU" "apps/gpu/DrivenCavityMultiGPU/drivencavity_regressiontest_4gpu.cfg"

echo $'\n\n\n\n---Second test: SphereMultiGPU on 4 GPUs\n\n'
mpirun -np 4 "./build/bin/SphereMultiGPU"        "apps/gpu/SphereMultiGPU/sphere_regressiontest_4gpu.cfg"