#!/bin/bash -l

#SBATCH --partition=gpu01_queue
#SBATCH --nodes=2
#SBATCH --time=10:00:00
#SBATCH --job-name=Regr8GPU
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:4
#SBATCH --output=multigpu_test/slurm8GPU.out
##SBATCH --exclusive

module purge 
module load comp/gcc/10.2.0
module load mpi/openmpi/4.0.5_gcc_9.3/openmpi
module load cuda/11.3
module load comp/git/2.27.0
PATH=/home/irmb/tools/cmake-3.20.3-linux-x86_64/bin:$PATH

module list

cd multigpu_test
rm -r build && mkdir -p build
cd build
cmake .. -DBUILD_VF_GPU=ON -DCMAKE_CUDA_ARCHITECTURES=60 -DUSER_APPS=apps/gpu/LBM/DrivenCavityMultiGPU\;apps/gpu/LBM/SphereScaling
make -j 16
cd ..
mkdir -p output

echo $'\n\n\n\n---First test: DrivenCavityMultiGPU on 8 GPUs\n\n'
mpirun -np 8 "./build/bin/DrivenCavityMultiGPU" "apps/gpu/LBM/DrivenCavityMultiGPU/configPhoenix8GPU_regressionTest.txt"

echo $'\n\n\n\n---Second test: SphereScaling on 8 GPUs\n\n'
mpirun -np 8 "./build/bin/SphereScaling"        "apps/gpu/LBM/SphereScaling/configPhoenix8GPU_regressionTest.txt"