#!/bin/bash -l

#SBATCH --partition=gpu01_queue
#SBATCH --nodes=1
#SBATCH --time=10:00:00
#SBATCH --job-name=Regr4GPU
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:4
#SBATCH --output=multigpu_test/slurm4GPU.out
##SBATCH --exclusive

module purge 
module load comp/ccache/4.1 # loads comp/gcc/9.3.0 
module load mpi/openmpi/4.0.5_gcc_9.3/openmpi 
module load cuda/11.3
module load comp/git/2.27.0
PATH=/home/irmb/tools/cmake-3.20.3-linux-x86_64/bin:$PATH

module list

cd multigpu_test
mkdir -p build
cd build
cmake .. -DBUILD_VF_GPU=ON -DCMAKE_CUDA_ARCHITECTURES=60 -DUSER_APPS="apps/gpu/LBM/DrivenCavityMultiGPU";"apps/gpu/LBM/SphereScaling"
make -j 16
cd ..
mkdir -p output

echo $'\n\n First test: DrivenCavityMultiGPU on 4 GPUs\n'
mpirun -np 4 "./build/bin/DrivenCavityMultiGPU" "configPhoenix4GPU_regressionTest.txt"

echo $'\n\n First test: SphereScaling on 4 GPUs\n'
mpirun -np 4 "./build/bin/SphereScaling"        "configPhoenix4GPU_regressionTest.txt"