#!/bin/bash -l

#SBATCH --partition=gpu01_queue
#SBATCH --nodes=1
#SBATCH --time=03:00:00
#SBATCH --job-name=Regr4GPU
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:4
#SBATCH --output=multigpu_test/slurm4GPU.out
##SBATCH --exclusive

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURM_TASKS_PER_NODE"=$SLURM_TASKS_PER_NODE

module purge
module load comp/gcc/10.2.0
module load mpi/openmpi/4.0.5_gcc_9.3/openmpi
module load cuda/11.3
module load comp/git/2.27.0
PATH=/home/irmb/tools/cmake-3.20.3-linux-x86_64/bin:$PATH

module list

cd multigpu_test
rm -rf build && mkdir -p build
cd build
cmake .. -DBUILD_VF_GPU=ON -DCMAKE_CUDA_ARCHITECTURES=60 -DUSER_APPS=apps/gpu/LBM/DrivenCavityMultiGPU\;apps/gpu/LBM/SphereScaling
make -j 16
cd ..
mkdir -p output

echo $'\n\n\n\n---First test: DrivenCavityMultiGPU on 4 GPUs\n\n'
mpirun -np 4 "./build/bin/DrivenCavityMultiGPU" "apps/gpu/LBM/DrivenCavityMultiGPU/configPhoenix4GPU_regressionTest.txt"

echo $'\n\n\n\n---Second test: SphereScaling on 4 GPUs\n\n'
mpirun -np 4 "./build/bin/SphereScaling"        "apps/gpu/LBM/SphereScaling/configPhoenix4GPU_regressionTest.txt"