# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright © VirtualFluids Project contributors, see AUTHORS.md in root folder

# -*- coding: utf-8 -*-
"""
Created on Tue Dec  6 13:21:27 2022

@author: kutscher
"""

filename = "d:/temp/VF/4/MultiphaseScaleDistributionLBMKernel.cpp"

#read input file
fin = open(filename, "rt")
#read file contents to string
data = fin.read()
#replace all occurrences of the required string
data = data.replace('[REST]','[d000]')
data = data.replace('[TNE]', '[DIR_PPP]')
data = data.replace('[TNW]', '[DIR_MPP]')
data = data.replace('[TSE]', '[DIR_PMP]')
data = data.replace('[TSW]', '[DIR_MMP]')
data = data.replace('[BNE]', '[DIR_PPM]')
data = data.replace('[BNW]', '[DIR_MPM]')
data = data.replace('[BSE]', '[DIR_PMM]')
data = data.replace('[BSW]', '[DIR_MMM]')
data = data.replace('[NE]',  '[DIR_PP0]')
data = data.replace('[SW]',  '[DIR_MM0]')
data = data.replace('[SE]',  '[DIR_PM0]')
data = data.replace('[NW]',  '[DIR_MP0]')
data = data.replace('[TE]',  '[DIR_P0P]')
data = data.replace('[BW]',  '[DIR_M0M]')
data = data.replace('[BE]',  '[DIR_P0M]')
data = data.replace('[TW]',  '[DIR_M0P]')
data = data.replace('[TN]',  '[DIR_0PP]')
data = data.replace('[BS]',  '[DIR_0MM]')
data = data.replace('[BN]',  '[DIR_0PM]')
data = data.replace('[TS]',  '[DIR_0MP]')
data = data.replace('[NE]', '[DIR_PP0]')
data = data.replace('[SW]', '[DIR_MM0]')
data = data.replace('[SE]', '[DIR_PM0]')
data = data.replace('[NW]', '[DIR_MP0]')
data = data.replace('[TE]', '[DIR_P0P]')
data = data.replace('[BW]', '[DIR_M0M]')
data = data.replace('[BE]', '[DIR_P0M]')
data = data.replace('[TW]', '[DIR_M0P]')
data = data.replace('[TN]', '[DIR_0PP]')
data = data.replace('[BS]', '[DIR_0MM]')
data = data.replace('[BN]', '[DIR_0PM]')
data = data.replace('[TS]', '[DIR_0MP]')
data = data.replace('[E]',   '[dP00]')
data = data.replace('[W]',   '[dM00]')
data = data.replace('[N]',   '[DIR_0P0]')
data = data.replace('[S]',   '[DIR_0M0]')
data = data.replace('[T]',   '[DIR_00P]')
data = data.replace('[B]',   '[DIR_00M]')

# data = data.replace('[REST]','[d000]')
# data = data.replace('[E  ]', '[dP00]')
# data = data.replace('[W  ]', '[dM00]')
# data = data.replace('[N  ]', '[DIR_0P0]')
# data = data.replace('[S  ]', '[DIR_0M0]')
# data = data.replace('[T  ]', '[DIR_00P]')
# data = data.replace('[B  ]', '[DIR_00M]')
# data = data.replace('[NE ]', '[DIR_PP0]')
# data = data.replace('[SW ]', '[DIR_MM0]')
# data = data.replace('[SE ]', '[DIR_PM0]')
# data = data.replace('[NW ]', '[DIR_MP0]')
# data = data.replace('[TE ]', '[DIR_P0P]')
# data = data.replace('[BW ]', '[DIR_M0M]')
# data = data.replace('[BE ]', '[DIR_P0M]')
# data = data.replace('[TW ]', '[DIR_M0P]')
# data = data.replace('[TN ]', '[DIR_0PP]')
# data = data.replace('[BS ]', '[DIR_0MM]')
# data = data.replace('[BN ]', '[DIR_0PM]')
# data = data.replace('[TS ]', '[DIR_0MP]')
# data = data.replace('[TNE]', '[DIR_PPP]')
# data = data.replace('[TNW]', '[DIR_MPP]')
# data = data.replace('[TSE]', '[DIR_PMP]')
# data = data.replace('[TSW]', '[DIR_MMP]')
# data = data.replace('[BNE]', '[DIR_PPM]')
# data = data.replace('[BNW]', '[DIR_MPM]')
# data = data.replace('[BSE]', '[DIR_PMM]')
# data = data.replace('[BSW]', '[DIR_MMM]')

# data = data.replace('D3Q27System::REST','[d000]')
# data = data.replace('D3Q27System::E', '[dP00]')
# data = data.replace('D3Q27System::W', '[dM00]')
# data = data.replace('D3Q27System::N', '[DIR_0P0]')
# data = data.replace('D3Q27System::S', '[DIR_0M0]')
# data = data.replace('D3Q27System::T', '[DIR_00P]')
# data = data.replace('D3Q27System::B', '[DIR_00M]')
# data = data.replace('D3Q27System::NE', '[DIR_PP0]')
# data = data.replace('D3Q27System::SW', '[DIR_MM0]')
# data = data.replace('D3Q27System::SE', '[DIR_PM0]')
# data = data.replace('D3Q27System::NW', '[DIR_MP0]')
# data = data.replace('D3Q27System::TE', '[DIR_P0P]')
# data = data.replace('D3Q27System::BW', '[DIR_M0M]')
# data = data.replace('D3Q27System::BE', '[DIR_P0M]')
# data = data.replace('D3Q27System::TW', '[DIR_M0P]')
# data = data.replace('D3Q27System::TN', '[DIR_0PP]')
# data = data.replace('D3Q27System::BS', '[DIR_0MM]')
# data = data.replace('D3Q27System::BN', '[DIR_0PM]')
# data = data.replace('D3Q27System::TS', '[DIR_0MP]')
# data = data.replace('D3Q27System::TNE', '[DIR_PPP]')
# data = data.replace('D3Q27System::TNW', '[DIR_MPP]')
# data = data.replace('D3Q27System::TSE', '[DIR_PMP]')
# data = data.replace('D3Q27System::TSW', '[DIR_MMP]')
# data = data.replace('D3Q27System::BNE', '[DIR_PPM]')
# data = data.replace('D3Q27System::BNW', '[DIR_MPM]')
# data = data.replace('D3Q27System::BSE', '[DIR_PMM]')
# data = data.replace('D3Q27System::BSW', '[DIR_MMM]')

# data = data.replace('REST)','d000)')
# data = data.replace('TNE)', 'DIR_PPP)')
# data = data.replace('TNW)', 'DIR_MPP)')
# data = data.replace('TSE)', 'DIR_PMP)')
# data = data.replace('TSW)', 'DIR_MMP)')
# data = data.replace('BNE)', 'DIR_PPM)')
# data = data.replace('BNW)', 'DIR_MPM)')
# data = data.replace('BSE)', 'DIR_PMM)')
# data = data.replace('BSW)', 'DIR_MMM)')
# data = data.replace('NE)',  'DIR_PP0)')
# data = data.replace('SW)',  'DIR_MM0)')
# data = data.replace('SE)',  'DIR_PM0)')
# data = data.replace('NW)',  'DIR_MP0)')
# data = data.replace('TE)',  'DIR_P0P)')
# data = data.replace('BW)',  'DIR_M0M)')
# data = data.replace('BE)',  'DIR_P0M)')
# data = data.replace('TW)',  'DIR_M0P)')
# data = data.replace('TN)',  'DIR_0PP)')
# data = data.replace('BS)',  'DIR_0MM)')
# data = data.replace('BN)',  'DIR_0PM)')
# data = data.replace('TS)',  'DIR_0MP)')
# data = data.replace('E)',   'dP00)')
# data = data.replace('W)',   'dM00)')
# data = data.replace('N)',   'DIR_0P0)')
# data = data.replace('S)',   'DIR_0M0)')
# data = data.replace('T)',   'DIR_00P)')
# data = data.replace('B)',   'DIR_00M)')

# data = data.replace('REST','d000')
# data = data.replace('TNE', 'DIR_PPP')
# data = data.replace('TNW', 'DIR_MPP')
# data = data.replace('TSE', 'DIR_PMP')
# data = data.replace('TSW', 'DIR_MMP')
# data = data.replace('BNE', 'DIR_PPM')
# data = data.replace('BNW', 'DIR_MPM')
# data = data.replace('BSE', 'DIR_PMM')
# data = data.replace('BSW', 'DIR_MMM')
# data = data.replace('NE',  'DIR_PP0')
# data = data.replace('SW',  'DIR_MM0')
# data = data.replace('SE',  'DIR_PM0')
# data = data.replace('NW',  'DIR_MP0')
# data = data.replace('TE',  'DIR_P0P')
# data = data.replace('BW',  'DIR_M0M')
# data = data.replace('BE',  'DIR_P0M')
# data = data.replace('TW',  'DIR_M0P')
# data = data.replace('TN',  'DIR_0PP')
# data = data.replace('BS',  'DIR_0MM')
# data = data.replace('BN',  'DIR_0PM')
# data = data.replace('TS',  'DIR_0MP')
# data = data.replace('E',   'dP00')
# data = data.replace('W',   'dM00')
# data = data.replace('N',   'DIR_0P0')
# data = data.replace('S',   'DIR_0M0')
# data = data.replace('T',   'DIR_00P')
# data = data.replace('B',   'DIR_00M')

# text = 'bat::ball'

# # replace b with c
# replaced_text = text.replace('b', 'c')
# print(replaced_text)


#close the input file
fin.close()
#open the input file in write mode
fin = open(filename, "wt")
#overrite the input file with the resulting data
fin.write(data)
#close the file
fin.close()