
#ifndef LIGGGHTSCOUPLING_EXPORT_H
#define LIGGGHTSCOUPLING_EXPORT_H

#ifdef LIGGGHTSCOUPLING_STATIC_DEFINE
#  define LIGGGHTSCOUPLING_EXPORT
#  define LIGGGHTSCOUPLING_NO_EXPORT
#else
#  ifndef LIGGGHTSCOUPLING_EXPORT
#    ifdef LiggghtsCoupling_EXPORTS
        /* We are building this library */
#      define LIGGGHTSCOUPLING_EXPORT 
#    else
        /* We are using this library */
#      define LIGGGHTSCOUPLING_EXPORT 
#    endif
#  endif

#  ifndef LIGGGHTSCOUPLING_NO_EXPORT
#    define LIGGGHTSCOUPLING_NO_EXPORT 
#  endif
#endif

#ifndef LIGGGHTSCOUPLING_DEPRECATED
#  define LIGGGHTSCOUPLING_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef LIGGGHTSCOUPLING_DEPRECATED_EXPORT
#  define LIGGGHTSCOUPLING_DEPRECATED_EXPORT LIGGGHTSCOUPLING_EXPORT LIGGGHTSCOUPLING_DEPRECATED
#endif

#ifndef LIGGGHTSCOUPLING_DEPRECATED_NO_EXPORT
#  define LIGGGHTSCOUPLING_DEPRECATED_NO_EXPORT LIGGGHTSCOUPLING_NO_EXPORT LIGGGHTSCOUPLING_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef LIGGGHTSCOUPLING_NO_DEPRECATED
#    define LIGGGHTSCOUPLING_NO_DEPRECATED
#  endif
#endif

#endif /* LIGGGHTSCOUPLING_EXPORT_H */
