
#ifndef MULTIPHASEFLOW_EXPORT_H
#define MULTIPHASEFLOW_EXPORT_H

#ifdef MULTIPHASEFLOW_STATIC_DEFINE
#  define MULTIPHASEFLOW_EXPORT
#  define MULTIPHASEFLOW_NO_EXPORT
#else
#  ifndef MULTIPHASEFLOW_EXPORT
#    ifdef MultiphaseFlow_EXPORTS
        /* We are building this library */
#      define MULTIPHASEFLOW_EXPORT 
#    else
        /* We are using this library */
#      define MULTIPHASEFLOW_EXPORT 
#    endif
#  endif

#  ifndef MULTIPHASEFLOW_NO_EXPORT
#    define MULTIPHASEFLOW_NO_EXPORT 
#  endif
#endif

#ifndef MULTIPHASEFLOW_DEPRECATED
#  define MULTIPHASEFLOW_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MULTIPHASEFLOW_DEPRECATED_EXPORT
#  define MULTIPHASEFLOW_DEPRECATED_EXPORT MULTIPHASEFLOW_EXPORT MULTIPHASEFLOW_DEPRECATED
#endif

#ifndef MULTIPHASEFLOW_DEPRECATED_NO_EXPORT
#  define MULTIPHASEFLOW_DEPRECATED_NO_EXPORT MULTIPHASEFLOW_NO_EXPORT MULTIPHASEFLOW_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef MULTIPHASEFLOW_NO_DEPRECATED
#    define MULTIPHASEFLOW_NO_DEPRECATED
#  endif
#endif

#endif /* MULTIPHASEFLOW_EXPORT_H */
