
#ifndef NONNEWTONIANFLUIDS_EXPORT_H
#define NONNEWTONIANFLUIDS_EXPORT_H

#ifdef NONNEWTONIANFLUIDS_STATIC_DEFINE
#  define NONNEWTONIANFLUIDS_EXPORT
#  define NONNEWTONIANFLUIDS_NO_EXPORT
#else
#  ifndef NONNEWTONIANFLUIDS_EXPORT
#    ifdef NonNewtonianFluids_EXPORTS
        /* We are building this library */
#      define NONNEWTONIANFLUIDS_EXPORT 
#    else
        /* We are using this library */
#      define NONNEWTONIANFLUIDS_EXPORT 
#    endif
#  endif

#  ifndef NONNEWTONIANFLUIDS_NO_EXPORT
#    define NONNEWTONIANFLUIDS_NO_EXPORT 
#  endif
#endif

#ifndef NONNEWTONIANFLUIDS_DEPRECATED
#  define NONNEWTONIANFLUIDS_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef NONNEWTONIANFLUIDS_DEPRECATED_EXPORT
#  define NONNEWTONIANFLUIDS_DEPRECATED_EXPORT NONNEWTONIANFLUIDS_EXPORT NONNEWTONIANFLUIDS_DEPRECATED
#endif

#ifndef NONNEWTONIANFLUIDS_DEPRECATED_NO_EXPORT
#  define NONNEWTONIANFLUIDS_DEPRECATED_NO_EXPORT NONNEWTONIANFLUIDS_NO_EXPORT NONNEWTONIANFLUIDS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef NONNEWTONIANFLUIDS_NO_DEPRECATED
#    define NONNEWTONIANFLUIDS_NO_DEPRECATED
#  endif
#endif

#endif /* NONNEWTONIANFLUIDS_EXPORT_H */
