INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/numerics/geometry3d/CMakePackage.txt)
INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/numerics/geometry3d/creator/CMakePackage.txt)
INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/numerics/geometry3d/KdTree/CMakePackage.txt)
INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/basics/objects/CMakePackage.txt)
INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/basics/memory/CMakePackage.txt)
INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/basics/utilities/CMakePackage.txt)
INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/basics/container/CMakePackage.txt)
INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/basics/writer/CMakePackage.txt)
INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/basics/transmitter/CMakePackage.txt)

INCLUDE(${SOURCE_ROOT}/VirtualFluidsBasic/IncludsList.cmake)