
#ifndef VIRTUALFLUIDSCORE_EXPORT_H
#define VIRTUALFLUIDSCORE_EXPORT_H

#ifdef VIRTUALFLUIDSCORE_STATIC_DEFINE
#  define VIRTUALFLUIDSCORE_EXPORT
#  define VIRTUALFLUIDSCORE_NO_EXPORT
#else
#  ifndef VIRTUALFLUIDSCORE_EXPORT
#    ifdef VirtualFluidsCore_EXPORTS
        /* We are building this library */
#      define VIRTUALFLUIDSCORE_EXPORT 
#    else
        /* We are using this library */
#      define VIRTUALFLUIDSCORE_EXPORT 
#    endif
#  endif

#  ifndef VIRTUALFLUIDSCORE_NO_EXPORT
#    define VIRTUALFLUIDSCORE_NO_EXPORT 
#  endif
#endif

#ifndef VIRTUALFLUIDSCORE_DEPRECATED
#  define VIRTUALFLUIDSCORE_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef VIRTUALFLUIDSCORE_DEPRECATED_EXPORT
#  define VIRTUALFLUIDSCORE_DEPRECATED_EXPORT VIRTUALFLUIDSCORE_EXPORT VIRTUALFLUIDSCORE_DEPRECATED
#endif

#ifndef VIRTUALFLUIDSCORE_DEPRECATED_NO_EXPORT
#  define VIRTUALFLUIDSCORE_DEPRECATED_NO_EXPORT VIRTUALFLUIDSCORE_NO_EXPORT VIRTUALFLUIDSCORE_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VIRTUALFLUIDSCORE_NO_DEPRECATED
#    define VIRTUALFLUIDSCORE_NO_DEPRECATED
#  endif
#endif

#endif /* VIRTUALFLUIDSCORE_EXPORT_H */
