#!/bin/bash
#SBATCH -J PyFluidsTest
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8

#SBATCH --mem-per-cpu=30000
#SBATCH --time=02:00:00
#SBATCH --partition=shortrun_small

source .bashrc

echo "PyFluids Poiseuille Test Case"
echo "Number of tasks: ${SLURM_NTASKS}"

export PYFLUIDS_SCALE_LEVEL=0
mpiexec -np "$SLURM_NTASKS" singularity exec SingularityImages/VirtualFluidsMPICH.sif python3 /VirtualFluids_dev/Python/poiseuille/simulation_runner.py

export PYFLUIDS_SCALE_LEVEL=1
mpiexec -np "$SLURM_NTASKS" singularity exec SingularityImages/VirtualFluidsMPICH.sif python3 /VirtualFluids_dev/Python/poiseuille/simulation_runner.py

export PYFLUIDS_SCALE_LEVEL=2
mpiexec -np "$SLURM_NTASKS" singularity exec SingularityImages/VirtualFluidsMPICH.sif python3 /VirtualFluids_dev/Python/poiseuille/simulation_runner.py

singularity exec SingularityImages/VirtualFluidsMPICH.sif python3 /VirtualFluids_dev/Python/poiseuille/SlurmTests/poiseuille/evaluator.py
