#add_subdirectory(${APPS_ROOT_CPU}/CouetteFlow)
#add_subdirectory(${APPS_ROOT_CPU}/sphere)
#add_subdirectory(${APPS_ROOT_CPU}/FlowAroundCylinder)
#add_subdirectory(${APPS_ROOT_CPU}/LaminarTubeFlow)
#add_subdirectory(${APPS_ROOT_CPU}/ConvectionOfVortex)
#add_subdirectory(${APPS_ROOT_CPU}/PoiseuilleFlowPlates)



#add_subdirectory(tests)
#add_subdirectory(Applications/gridRf)
#add_subdirectory(Applications/greenvortex)
# add_subdirectory(Applications/micropart)
#add_subdirectory(Applications/vfscript)
#add_subdirectory(Applications/reefer)
#add_subdirectory(Applications/bananas)
#add_subdirectory(Applications/test1)
#add_subdirectory(Applications/test2)
#add_subdirectory(Applications/bananas2)
# add_subdirectory(Applications/plate)
# add_subdirectory(Applications/plate2)
# add_subdirectory(Applications/LaminarTubeFlowConv)
#add_subdirectory(Applications/cylinderSt)
#add_subdirectory(Applications/mpichTest)
# add_subdirectory(Applications/block_test)
# add_subdirectory(Applications/bond_test)
# add_subdirectory(Applications/bond_benchmark)
# add_subdirectory(Applications/musis)
##add_subdirectory(Applications/Hagen_Poiseuille_flow)
##add_subdirectory(Applications/Hagen_Poiseuille_flow2)
##add_subdirectory(Applications/mpi_benchmark)
# add_subdirectory(Applications/shear)
# add_subdirectory(Applications/wing)
# add_subdirectory(Applications/bKanal)
# add_subdirectory(Applications/bKanal2)
# add_subdirectory(Applications/bKanalAv)
# add_subdirectory(Applications/fetol_demo)
# add_subdirectory(Applications/insitu_demo)
# add_subdirectory(Applications/insitu_demoserver)
# add_subdirectory(Applications/PlateWithPorousInlay)
# add_subdirectory(Applications/stick)
# add_subdirectory(Applications/band)
# add_subdirectory(Applications/bone)
# add_subdirectory(Applications/sbone)
# add_subdirectory(Applications/bbone)
# add_subdirectory(Applications/porplate2)
# add_subdirectory(Applications/BeadPack)
# add_subdirectory(Applications/town)
##add_subdirectory(Applications/perm)
#add_subdirectory(Applications/pChannel)
#add_subdirectory(Applications/pDisk)
#add_subdirectory(Applications/BoxBenchmark)
#add_subdirectory(Applications/DHIT)
#add_subdirectory(Applications/DLR-F16)
#add_subdirectory(Applications/DLR-F16-Solid)
#add_subdirectory(Applications/DLR-F16-Porous)
#add_subdirectory(Applications/aperm)
#add_subdirectory(Applications/f16test)
#add_subdirectory(Applications/mirror)
#add_subdirectory(Applications/levels)
#add_subdirectory(Applications/AcousticPulse)
#add_subdirectory(Applications/screw)
#add_subdirectory(Applications/InterfaceTest)
#add_subdirectory(Applications/teperm)
#add_subdirectory(Applications/Thermoplast)
#add_subdirectory(Applications/bChannelA)
#add_subdirectory(Applications/ConvectionOfVortex)
#add_subdirectory(Applications/CheckpointConverter)
#add_subdirectory(Applications/bChannelVA)
#add_subdirectory(Applications/OrganPipe)
#add_subdirectory(Applications/LidDrivenCavity)

if(BUILD_USE_BOOST)
    add_subdirectory(${APPS_ROOT_CPU}/TPMSRow)
endif()
