INCLUDE_DIRECTORIES(${APPS_ROOT_CPU})
INCLUDE(${SOURCE_PATH}/cpu/VirtualFluidsCore/IncludsList.cmake)

INCLUDE_DIRECTORIES(${SOURCE_PATH}/cpu/VirtualFluidsCore)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics/geometry3d)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics/geometry3d/Creator)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics/geometry3d/KdTree)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics/basics/container)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics/basics/memory)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics/basics/objects)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics/basics/transmiitter)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics/basics/utilities)
INCLUDE_DIRECTORIES(${SOURCE_PATH}/basics/basics/writer)
