INCLUDE_DIRECTORIES(${APPS_ROOT_CPU})
INCLUDE(${VF_SRC_DIR}/cpu/VirtualFluidsCore/IncludsList.cmake)

INCLUDE_DIRECTORIES(${VF_SRC_DIR}/cpu/VirtualFluidsCore)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics/geometry3d)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics/geometry3d/Creator)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics/geometry3d/KdTree)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics/basics/container)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics/basics/memory)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics/basics/objects)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics/basics/transmiitter)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics/basics/utilities)
INCLUDE_DIRECTORIES(${VF_SRC_DIR}/basics/basics/writer)
