class Logger:
    @staticmethod
    def change_log_path(path: str) -> None: ...
    @staticmethod
    def initialize_logger() -> None: ...

def vf_log_critical(message: str) -> None: ...
def vf_log_debug(message: str) -> None: ...
def vf_log_info(message: str) -> None: ...
def vf_log_trace(message: str) -> None: ...
def vf_log_warning(message: str) -> None: ...
