class Logger:
    def __init__(self, *args, **kwargs) -> None: ...
    def change_log_path(self) -> None: ...
    def initialize_logger(self) -> None: ...

def vf_log_critical(message: str) -> None: ...
def vf_log_debug(message: str) -> None: ...
def vf_log_info(message: str) -> None: ...
def vf_log_trace(message: str) -> None: ...
def vf_log_warning(message: str) -> None: ...
