#ifndef D3Q27_KERNELS_H
#define D3Q27_KERNELS_H

//random numbers
#include <curand.h>
#include <curand_kernel.h>

extern "C" __global__ void LB_Kernel_Casc27(doubflo s9,
                                            unsigned int* bcMatD,
                                            unsigned int* neighborX,
                                            unsigned int* neighborY,
                                            unsigned int* neighborZ,
                                            doubflo* DDStart,
                                            int size_Mat,
                                            bool EvenOrOdd); 

extern "C" __global__ void LB_Kernel_Casc_SP_27(  doubflo s9,
                                                  unsigned int* bcMatD,
                                                  unsigned int* neighborX,
                                                  unsigned int* neighborY,
                                                  unsigned int* neighborZ,
                                                  doubflo* DDStart,
                                                  int size_Mat,
                                                  bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Casc_SP_MS_27(   doubflo s9,
                                                      unsigned int* bcMatD,
                                                      unsigned int* neighborX,
                                                      unsigned int* neighborY,
                                                      unsigned int* neighborZ,
                                                      doubflo* DDStart,
                                                      int size_Mat,
                                                      bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Casc_SP_MS_OHM_27(  doubflo s9,
                                                         unsigned int* bcMatD,
                                                         unsigned int* neighborX,
                                                         unsigned int* neighborY,
                                                         unsigned int* neighborZ,
                                                         doubflo* DDStart,
                                                         int size_Mat,
                                                         bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Casc_Kum_SP_27(doubflo s9,
                                                    unsigned int* bcMatD,
                                                    unsigned int* neighborX,
                                                    unsigned int* neighborY,
                                                    unsigned int* neighborZ,
                                                    doubflo* DDStart,
                                                    int size_Mat,
                                                    bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_BGK_Plus_SP_27(doubflo omega,
													unsigned int* bcMatD,
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													doubflo* DDStart,
													int size_Mat,
													bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_BGK_Plus_Comp_SP_27(doubflo omega,
														 unsigned int* bcMatD,
														 unsigned int* neighborX,
														 unsigned int* neighborY,
														 unsigned int* neighborZ,
														 doubflo* DDStart,
														 int size_Mat,
														 bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_BGK_Comp_SP_27(doubflo omega,
													unsigned int* bcMatD,
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													doubflo* DDStart,
													int size_Mat,
													bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_BGK_SP_27( doubflo omega,
												unsigned int* bcMatD,
												unsigned int* neighborX,
												unsigned int* neighborY,
												unsigned int* neighborZ,
												doubflo* DDStart,
												int size_Mat,
												bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_MRT_SP_27( doubflo omega,
												unsigned int* bcMatD,
												unsigned int* neighborX,
												unsigned int* neighborY,
												unsigned int* neighborZ,
												doubflo* DDStart,
												int size_Mat,
												bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_MRT_Comp_SP_27(doubflo omega,
													unsigned int* bcMatD,
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													doubflo* DDStart,
													int size_Mat,
													bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Cumulant_D3Q27All4(doubflo omega,
														unsigned int* bcMatD,
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														doubflo* DDStart,
														int size_Mat,
														int level,
														doubflo* forces,
														bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Cumulant_D3Q27F3(	doubflo omega,
														unsigned int* bcMatD,
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														doubflo* DDStart,
														doubflo* F3,
														int size_Mat,
														int level,
														doubflo* forces,
														bool EvenOrOdd);

	
extern "C" __global__ void LB_Kernel_Kum_AA2016_Comp_Bulk_SP_27(doubflo omega,
																unsigned int* bcMatD,
																unsigned int* neighborX,
																unsigned int* neighborY,
																unsigned int* neighborZ,
																doubflo* DDStart,
																int size_Mat,
																int level,
																doubflo* forces,
																bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Kum_AA2016_Comp_SP_27(doubflo omega,
														   unsigned int* bcMatD,
														   unsigned int* neighborX,
														   unsigned int* neighborY,
														   unsigned int* neighborZ,
														   doubflo* DDStart,
														   int size_Mat,
														   int level,
														   doubflo* forces,
														   bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Kum_New_Comp_Sponge_SP_27(doubflo omega,
														       unsigned int* bcMatD,
														       unsigned int* neighborX,
														       unsigned int* neighborY,
														       unsigned int* neighborZ,
													           doubflo* coordX,
													           doubflo* coordY,
													           doubflo* coordZ,
														       doubflo* DDStart,
														       int size_Mat,
														       bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Kum_1h_SP_27(  doubflo omega,
													doubflo deltaPhi,
													doubflo angularVelocity,
													unsigned int* bcMatD,
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													doubflo* coordX,
													doubflo* coordY,
													doubflo* coordZ,
													doubflo* DDStart,
													int size_Mat,
													bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Cascade_SP_27( doubflo s9,
													unsigned int* bcMatD,
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													doubflo* DDStart,
													int size_Mat,
													bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Cascade_Comp_SP_27(doubflo s9,
														unsigned int* bcMatD,
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														doubflo* DDStart,
														int size_Mat,
														bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Kum_New_SP_27( doubflo s9,
													unsigned int* bcMatD,
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													doubflo* DDStart,
													int size_Mat,
													bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Kum_New_Comp_Bulk_SP_27(doubflo omega,
															 unsigned int* bcMatD,
															 unsigned int* neighborX,
															 unsigned int* neighborY,
															 unsigned int* neighborZ,
															 doubflo* DDStart,
															 int size_Mat,
															 int level,
															 doubflo* forces,
															 bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Kum_New_Comp_SP_27(doubflo omega,
														unsigned int* bcMatD,
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														doubflo* DDStart,
														int size_Mat,
														int level,
														doubflo* forces,
														bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Kum_IsoTest_SP_27( doubflo omega,
														unsigned int* bcMatD,
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														doubflo* DDStart,
														doubflo* dxxUx,
														doubflo* dyyUy,
														doubflo* dzzUz,
														int size_Mat,
														bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Kum_Comp_SP_27(doubflo s9,
													unsigned int* bcMatD,
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													doubflo* DDStart,
													int size_Mat,
													bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_Wale_Cum_One_Comp_SP_27(doubflo omega,
															 unsigned int* bcMatD,
															 unsigned int* neighborX,
															 unsigned int* neighborY,
															 unsigned int* neighborZ,
															 unsigned int* neighborWSB,
															 doubflo* veloX,
															 doubflo* veloY,
															 doubflo* veloZ,
															 doubflo* DDStart,
															 int size_Mat,
															 int level,
															 doubflo* forces,
															 bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_ThS7(doubflo diffusivity,
                                          unsigned int* bcMatD,
                                          unsigned int* neighborX,
                                          unsigned int* neighborY,
                                          unsigned int* neighborZ,
                                          doubflo* DDStart,
                                          doubflo* DD7,
                                          int size_Mat,
                                          bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_ThS27(doubflo diffusivity,
                                           unsigned int* bcMatD,
                                           unsigned int* neighborX,
                                           unsigned int* neighborY,
                                           unsigned int* neighborZ,
                                           doubflo* DDStart,
                                           doubflo* DD27,
                                           int size_Mat,
                                           bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_AD_Incomp_7( doubflo diffusivity,
												  unsigned int* bcMatD,
												  unsigned int* neighborX,
												  unsigned int* neighborY,
												  unsigned int* neighborZ,
												  doubflo* DDStart,
												  doubflo* DD7,
												  int size_Mat,
												  bool EvenOrOdd);

extern "C" __global__ void LB_Kernel_AD_Incomp_27( doubflo diffusivity,
												   unsigned int* bcMatD,
												   unsigned int* neighborX,
												   unsigned int* neighborY,
												   unsigned int* neighborZ,
												   doubflo* DDStart,
												   doubflo* DD27,
												   int size_Mat,
												   bool EvenOrOdd);

extern "C" __global__ void LBInit27( int myid,
                                     int numprocs,
                                     doubflo u0,
                                     unsigned int* geoD,
                                     unsigned int* neighborX,
                                     unsigned int* neighborY,
                                     unsigned int* neighborZ,
                                     doubflo* vParabel,
                                     unsigned int size_Mat,
                                     unsigned int grid_nx, 
                                     unsigned int grid_ny, 
                                     unsigned int grid_nz, 
                                     doubflo* DD,
                                     int lev,
                                     int maxlev);

extern "C" __global__ void LBInitF3(unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int* geoD,
									doubflo* rho,
									doubflo* ux,
									doubflo* uy,
									doubflo* uz,
									unsigned int size_Mat,
									doubflo* G6,
									bool EvenOrOdd);

extern "C" __global__ void LBInitSP27( unsigned int* neighborX,
                                       unsigned int* neighborY,
                                       unsigned int* neighborZ,
                                       unsigned int* geoD,
                                       doubflo* rho,
                                       doubflo* ux,
                                       doubflo* uy,
                                       doubflo* uz,
                                       unsigned int size_Mat,
                                       doubflo* DD,
                                       bool EvenOrOdd);

extern "C" __global__ void LBInitCompSP27( unsigned int* neighborX,
										   unsigned int* neighborY,
										   unsigned int* neighborZ,
										   unsigned int* geoD,
										   doubflo* rho,
										   doubflo* ux,
										   doubflo* uy,
										   doubflo* uz,
										   unsigned int size_Mat,
										   doubflo* DD,
										   bool EvenOrOdd);

extern "C" __global__ void LBInitThS7( unsigned int* neighborX,
                                       unsigned int* neighborY,
                                       unsigned int* neighborZ,
                                       unsigned int* geoD,
                                       doubflo* Conc,
                                       doubflo* ux,
                                       doubflo* uy,
                                       doubflo* uz,
                                       unsigned int size_Mat,
                                       doubflo* DD7,
                                       bool EvenOrOdd);

extern "C" __global__ void LBInitThS27(unsigned int* neighborX,
                                       unsigned int* neighborY,
                                       unsigned int* neighborZ,
                                       unsigned int* geoD,
                                       doubflo* Conc,
                                       doubflo* ux,
                                       doubflo* uy,
                                       doubflo* uz,
                                       unsigned int size_Mat,
                                       doubflo* DD27,
                                       bool EvenOrOdd);

extern "C" __global__ void LBInitIncompAD7(unsigned int* neighborX,
										   unsigned int* neighborY,
										   unsigned int* neighborZ,
										   unsigned int* geoD,
										   doubflo* Conc,
										   doubflo* ux,
										   doubflo* uy,
										   doubflo* uz,
										   unsigned int size_Mat,
										   doubflo* DD7,
										   bool EvenOrOdd);

extern "C" __global__ void LBInitIncompAD27(unsigned int* neighborX,
										    unsigned int* neighborY,
										    unsigned int* neighborZ,
										    unsigned int* geoD,
										    doubflo* Conc,
										    doubflo* ux,
										    doubflo* uy,
										    doubflo* uz,
										    unsigned int size_Mat,
										    doubflo* DD27,
										    bool EvenOrOdd);

extern "C" __global__ void LBCalcMac27( doubflo* vxD,
                                        doubflo* vyD,
                                        doubflo* vzD,
                                        doubflo* rhoD,
                                        unsigned int* neighborX,
                                        unsigned int* neighborY,
                                        unsigned int* neighborZ,
                                        unsigned int* geoD,
                                        unsigned int size_Mat,
                                        doubflo* DD,
                                        bool evenOrOdd);

extern "C" __global__ void LBCalcMacSP27( doubflo* vxD,
                                          doubflo* vyD,
                                          doubflo* vzD,
                                          doubflo* rhoD,
                                          doubflo* pressD,
                                          unsigned int* geoD,
                                          unsigned int* neighborX,
                                          unsigned int* neighborY,
                                          unsigned int* neighborZ,
                                          unsigned int size_Mat,
                                          doubflo* DD,
                                          bool evenOrOdd);

extern "C" __global__ void LBCalcMacCompSP27( doubflo* vxD,
											  doubflo* vyD,
											  doubflo* vzD,
											  doubflo* rhoD,
											  doubflo* pressD,
											  unsigned int* geoD,
											  unsigned int* neighborX,
											  unsigned int* neighborY,
											  unsigned int* neighborZ,
											  unsigned int size_Mat,
											  doubflo* DD,
											  bool evenOrOdd);

extern "C" __global__ void LBCalcMacThS7( doubflo* Conc,
                                          unsigned int* geoD,
                                          unsigned int* neighborX,
                                          unsigned int* neighborY,
                                          unsigned int* neighborZ,
                                          unsigned int size_Mat,
                                          doubflo* DD7,
                                          bool evenOrOdd);

extern "C" __global__ void GetPlaneConcThS7(doubflo* Conc,
								            int* kPC,
								            unsigned int numberOfPointskPC,
											unsigned int* geoD,
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat,
											doubflo* DD7,
											bool evenOrOdd);

extern "C" __global__ void GetPlaneConcThS27(doubflo* Conc,
								             int* kPC,
								             unsigned int numberOfPointskPC,
											 unsigned int* geoD,
											 unsigned int* neighborX,
											 unsigned int* neighborY,
											 unsigned int* neighborZ,
											 unsigned int size_Mat,
											 doubflo* DD27,
											 bool evenOrOdd);

extern "C" __global__ void LBCalcMacThS27(doubflo* Conc,
                                          unsigned int* geoD,
                                          unsigned int* neighborX,
                                          unsigned int* neighborY,
                                          unsigned int* neighborZ,
                                          unsigned int size_Mat,
                                          doubflo* DD27,
                                          bool evenOrOdd);

extern "C" __global__ void LBCalcMedSP27( doubflo* vxD,
                                          doubflo* vyD,
                                          doubflo* vzD,
                                          doubflo* rhoD,
                                          doubflo* pressD,
                                          unsigned int* geoD,
                                          unsigned int* neighborX,
                                          unsigned int* neighborY,
                                          unsigned int* neighborZ,
                                          unsigned int size_Mat,
                                          doubflo* DD,
                                          bool evenOrOdd);

extern "C" __global__ void LBCalcMedCompSP27( doubflo* vxD,
											  doubflo* vyD,
											  doubflo* vzD,
											  doubflo* rhoD,
											  doubflo* pressD,
											  unsigned int* geoD,
											  unsigned int* neighborX,
											  unsigned int* neighborY,
											  unsigned int* neighborZ,
											  unsigned int size_Mat,
											  doubflo* DD,
											  bool evenOrOdd);

extern "C" __global__ void LBCalcMacMedSP27( doubflo* vxD,
                                             doubflo* vyD,
                                             doubflo* vzD,
                                             doubflo* rhoD,
                                             doubflo* pressD,
                                             unsigned int* geoD,
                                             unsigned int* neighborX,
                                             unsigned int* neighborY,
                                             unsigned int* neighborZ,
                                             unsigned int tdiff,
                                             unsigned int size_Mat,
                                             bool evenOrOdd);

extern "C" __global__ void LBCalc2ndMomentsIncompSP27(  doubflo* kxyFromfcNEQ,
														doubflo* kyzFromfcNEQ,
														doubflo* kxzFromfcNEQ,
														doubflo* kxxMyyFromfcNEQ,
														doubflo* kxxMzzFromfcNEQ,
														unsigned int* geoD,
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														unsigned int size_Mat,
														doubflo* DD,
														bool evenOrOdd);

extern "C" __global__ void LBCalc2ndMomentsCompSP27(doubflo* kxyFromfcNEQ,
													doubflo* kyzFromfcNEQ,
													doubflo* kxzFromfcNEQ,
													doubflo* kxxMyyFromfcNEQ,
													doubflo* kxxMzzFromfcNEQ,
													unsigned int* geoD,
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													unsigned int size_Mat,
													doubflo* DD,
													bool evenOrOdd);

extern "C" __global__ void LBCalc3rdMomentsIncompSP27(  doubflo* CUMbbb,
														doubflo* CUMabc,
														doubflo* CUMbac,
														doubflo* CUMbca,
														doubflo* CUMcba,
														doubflo* CUMacb,
														doubflo* CUMcab,
														unsigned int* bcMatD,
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														doubflo* DDStart,
														int size_Mat,
														bool EvenOrOdd);

extern "C" __global__ void LBCalc3rdMomentsCompSP27(doubflo* CUMbbb,
													doubflo* CUMabc,
													doubflo* CUMbac,
													doubflo* CUMbca,
													doubflo* CUMcba,
													doubflo* CUMacb,
													doubflo* CUMcab,
													unsigned int* bcMatD,
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													doubflo* DDStart,
													int size_Mat,
													bool EvenOrOdd);

extern "C" __global__ void LBCalcHigherMomentsIncompSP27(   doubflo* CUMcbb,
															doubflo* CUMbcb,
															doubflo* CUMbbc,
															doubflo* CUMcca,
															doubflo* CUMcac,
															doubflo* CUMacc,
															doubflo* CUMbcc,
															doubflo* CUMcbc,
															doubflo* CUMccb,
															doubflo* CUMccc,
															unsigned int* bcMatD,
															unsigned int* neighborX,
															unsigned int* neighborY,
															unsigned int* neighborZ,
															doubflo* DDStart,
															int size_Mat,
															bool EvenOrOdd);

extern "C" __global__ void LBCalcHigherMomentsCompSP27( doubflo* CUMcbb,
														doubflo* CUMbcb,
														doubflo* CUMbbc,
														doubflo* CUMcca,
														doubflo* CUMcac,
														doubflo* CUMacc,
														doubflo* CUMbcc,
														doubflo* CUMcbc,
														doubflo* CUMccb,
														doubflo* CUMccc,
														unsigned int* bcMatD,
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														doubflo* DDStart,
														int size_Mat,
														bool EvenOrOdd);

extern "C" __global__ void LBCalcMeasurePoints(doubflo* vxMP,
                                               doubflo* vyMP,
                                               doubflo* vzMP,
                                               doubflo* rhoMP,
                                               unsigned int* kMP,
                                               unsigned int numberOfPointskMP,
                                               unsigned int MPClockCycle,
                                               unsigned int t,
                                               unsigned int* geoD,
                                               unsigned int* neighborX,
                                               unsigned int* neighborY,
                                               unsigned int* neighborZ,
                                               unsigned int size_Mat,
                                               doubflo* DD,
                                               bool evenOrOdd);

extern "C" __global__ void LB_BC_Press_East27( int nx, 
                                               int ny, 
                                               int tz, 
                                               unsigned int* bcMatD, 
                                               unsigned int* neighborX,
                                               unsigned int* neighborY,
                                               unsigned int* neighborZ,
                                               doubflo* DD, 
                                               unsigned int size_Mat, 
                                               bool evenOrOdd) ;

extern "C" __global__ void LB_BC_Vel_West_27( int nx, 
                                              int ny, 
                                              int nz, 
                                              int itz, 
                                              unsigned int* bcMatD, 
                                              unsigned int* neighborX,
                                              unsigned int* neighborY,
                                              unsigned int* neighborZ,
                                              doubflo* DD, 
                                              unsigned int size_Mat, 
                                              bool evenOrOdd, 
                                              doubflo u0x, 
                                              unsigned int grid_nx, 
                                              unsigned int grid_ny, 
                                              doubflo om); 

extern "C" __global__ void QDevice27(int inx,
                                     int iny,
                                     doubflo* DD, 
                                     int* k_Q, 
                                     doubflo* QQ,
                                     unsigned int sizeQ,
                                     int kQ, 
                                     doubflo minusomega, 
                                     unsigned int* neighborX,
                                     unsigned int* neighborY,
                                     unsigned int* neighborZ,
                                     unsigned int size_Mat, 
                                     bool evenOrOdd);

extern "C" __global__ void QDeviceComp27(int inx,
										 int iny,
										 doubflo* DD, 
										 int* k_Q, 
										 doubflo* QQ,
										 unsigned int sizeQ,
										 int kQ, 
										 doubflo minusomega, 
										 unsigned int* neighborX,
										 unsigned int* neighborY,
										 unsigned int* neighborZ,
										 unsigned int size_Mat, 
										 bool evenOrOdd);

extern "C" __global__ void QDevice3rdMomentsComp27(  int inx,
													 int iny,
													 doubflo* DD, 
													 int* k_Q, 
													 doubflo* QQ,
													 unsigned int sizeQ,
													 int kQ, 
													 doubflo minusomega, 
													 unsigned int* neighborX,
													 unsigned int* neighborY,
													 unsigned int* neighborZ,
													 unsigned int size_Mat, 
													 bool evenOrOdd);

extern "C" __global__ void QDeviceIncompHighNu27(int inx,
												 int iny,
												 doubflo* DD, 
												 int* k_Q, 
												 doubflo* QQ,
												 unsigned int sizeQ,
												 int kQ, 
												 doubflo om1, 
												 unsigned int* neighborX,
												 unsigned int* neighborY,
												 unsigned int* neighborZ,
												 unsigned int size_Mat, 
												 bool evenOrOdd);

extern "C" __global__ void QDeviceCompHighNu27(  int inx,
												 int iny,
												 doubflo* DD, 
												 int* k_Q, 
												 doubflo* QQ,
												 unsigned int sizeQ,
												 int kQ, 
												 doubflo om1, 
												 unsigned int* neighborX,
												 unsigned int* neighborY,
												 unsigned int* neighborZ,
												 unsigned int size_Mat, 
												 bool evenOrOdd);

extern "C" __global__ void QVelDevPlainBB27(doubflo* vx,
											doubflo* vy,
											doubflo* vz,
											doubflo* DD,
											int* k_Q, 
											doubflo* QQ,
											unsigned int sizeQ,
											int kQ, 
											doubflo om1, 
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat, 
											bool evenOrOdd);

extern "C" __global__ void QVelDevCouhette27(doubflo* vx,
											doubflo* vy,
											doubflo* vz,
											doubflo* DD,
											int* k_Q, 
											doubflo* QQ,
											unsigned int sizeQ,
											int kQ, 
											doubflo om1, 
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat, 
											bool evenOrOdd);

extern "C" __global__ void QVelDev1h27( int inx,
										int iny,
										doubflo* vx,
										doubflo* vy,
										doubflo* vz,
										doubflo* DD, 
										int* k_Q, 
										doubflo* QQ,
										unsigned int sizeQ,
										int kQ, 
										doubflo om1,
										doubflo Phi,
										doubflo angularVelocity,
										unsigned int* neighborX,
										unsigned int* neighborY,
										unsigned int* neighborZ,
										doubflo* coordX,
										doubflo* coordY,
										doubflo* coordZ,
										unsigned int size_Mat, 
										bool evenOrOdd);

extern "C" __global__ void QVelDevice27(int inx,
                                        int iny,
                                        doubflo* vx,
                                        doubflo* vy,
                                        doubflo* vz,
                                        doubflo* DD, 
                                        int* k_Q, 
                                        doubflo* QQ,
                                        unsigned int sizeQ,
                                        int kQ, 
                                        doubflo om1, 
                                        unsigned int* neighborX,
                                        unsigned int* neighborY,
                                        unsigned int* neighborZ,
                                        unsigned int size_Mat, 
                                        bool evenOrOdd);

extern "C" __global__ void QVelDeviceCompPlusSlip27(int inx,
													int iny,
													doubflo* vx,
													doubflo* vy,
													doubflo* vz,
													doubflo* DD, 
													int* k_Q, 
													doubflo* QQ,
													unsigned int sizeQ,
													int kQ, 
													doubflo om1, 
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													unsigned int size_Mat, 
													bool evenOrOdd);

extern "C" __global__ void QVelDeviceComp27(int inx,
											int iny,
											doubflo* vx,
											doubflo* vy,
											doubflo* vz,
											doubflo* DD, 
											int* k_Q, 
											doubflo* QQ,
											unsigned int sizeQ,
											int kQ, 
											doubflo om1, 
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat, 
											bool evenOrOdd);

extern "C" __global__ void QVelDeviceCompZeroPress27(   int inx,
														int iny,
														doubflo* vx,
														doubflo* vy,
														doubflo* vz,
														doubflo* DD, 
														int* k_Q, 
														doubflo* QQ,
														unsigned int sizeQ,
														//int kQ, 
														doubflo om1, 
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														unsigned int size_Mat, 
														bool evenOrOdd);

extern "C" __global__ void QVelDeviceIncompHighNu27(int inx,
													int iny,
													doubflo* vx,
													doubflo* vy,
													doubflo* vz,
													doubflo* DD, 
													int* k_Q, 
													doubflo* QQ,
													unsigned int sizeQ,
													int kQ, 
													doubflo om1, 
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													unsigned int size_Mat, 
													bool evenOrOdd);

extern "C" __global__ void QVelDeviceCompHighNu27(  int inx,
													int iny,
													doubflo* vx,
													doubflo* vy,
													doubflo* vz,
													doubflo* DD, 
													int* k_Q, 
													doubflo* QQ,
													unsigned int sizeQ,
													int kQ, 
													doubflo om1, 
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													unsigned int size_Mat, 
													bool evenOrOdd);

extern "C" __global__ void QVeloDeviceEQ27(doubflo* VeloX,
										   doubflo* VeloY,
										   doubflo* VeloZ,
                                           doubflo* DD, 
                                           int* k_Q, 
                                           int kQ, 
                                           doubflo om1, 
                                           unsigned int* neighborX,
                                           unsigned int* neighborY,
                                           unsigned int* neighborZ,
                                           unsigned int size_Mat, 
                                           bool evenOrOdd);

extern "C" __global__ void QSlipDevice27(doubflo* DD, 
                                         int* k_Q, 
                                         doubflo* QQ,
                                         unsigned int sizeQ,
                                         doubflo om1, 
                                         unsigned int* neighborX,
                                         unsigned int* neighborY,
                                         unsigned int* neighborZ,
                                         unsigned int size_Mat, 
                                         bool evenOrOdd);

extern "C" __global__ void QSlipDeviceComp27(doubflo* DD, 
											 int* k_Q, 
											 doubflo* QQ,
											 unsigned int sizeQ,
											 doubflo om1, 
											 unsigned int* neighborX,
											 unsigned int* neighborY,
											 unsigned int* neighborZ,
											 unsigned int size_Mat, 
											 bool evenOrOdd);

extern "C" __global__ void QSlipGeomDeviceComp27(doubflo* DD, 
												 int* k_Q, 
												 doubflo* QQ,
												 unsigned int sizeQ,
												 doubflo om1, 
												 doubflo* NormalX,
												 doubflo* NormalY,
												 doubflo* NormalZ,
												 unsigned int* neighborX,
												 unsigned int* neighborY,
												 unsigned int* neighborZ,
												 unsigned int size_Mat, 
												 bool evenOrOdd);

extern "C" __global__ void QSlipNormDeviceComp27(doubflo* DD, 
												 int* k_Q, 
												 doubflo* QQ,
												 unsigned int sizeQ,
												 doubflo om1, 
												 doubflo* NormalX,
												 doubflo* NormalY,
												 doubflo* NormalZ,
												 unsigned int* neighborX,
												 unsigned int* neighborY,
												 unsigned int* neighborZ,
												 unsigned int size_Mat, 
												 bool evenOrOdd);

extern "C" __global__ void QPressDevice27(int inx,
                                           int iny,
                                           doubflo* rhoBC,
                                           doubflo* DD, 
                                           int* k_Q, 
                                           doubflo* QQ,
                                           unsigned int sizeQ,
                                           int kQ, 
                                           doubflo om1, 
                                           unsigned int* neighborX,
                                           unsigned int* neighborY,
                                           unsigned int* neighborZ,
                                           unsigned int size_Mat, 
                                           bool evenOrOdd);

extern "C" __global__ void QPressDeviceAntiBB27(   doubflo* rhoBC,
												   doubflo* vx,
												   doubflo* vy,
												   doubflo* vz,
												   doubflo* DD, 
												   int* k_Q, 
												   doubflo* QQ,
												   int kQ, 
												   doubflo om1, 
												   unsigned int* neighborX,
												   unsigned int* neighborY,
												   unsigned int* neighborZ,
												   unsigned int size_Mat, 
												   bool evenOrOdd);

extern "C" __global__ void QPressDeviceFixBackflow27( doubflo* rhoBC,
                                                      doubflo* DD, 
                                                      int* k_Q, 
                                                      int kQ, 
                                                      doubflo om1, 
                                                      unsigned int* neighborX,
                                                      unsigned int* neighborY,
                                                      unsigned int* neighborZ,
                                                      unsigned int size_Mat, 
                                                      bool evenOrOdd);

extern "C" __global__ void QPressDeviceDirDepBot27(  doubflo* rhoBC,
                                                     doubflo* DD, 
                                                     int* k_Q, 
                                                     int kQ, 
                                                     doubflo om1, 
                                                     unsigned int* neighborX,
                                                     unsigned int* neighborY,
                                                     unsigned int* neighborZ,
                                                     unsigned int size_Mat, 
                                                     bool evenOrOdd);

extern "C" __global__ void QPressNoRhoDevice27(  doubflo* rhoBC,
												 doubflo* DD, 
												 int* k_Q, 
												 int* k_N, 
												 int kQ, 
												 doubflo om1, 
												 unsigned int* neighborX,
												 unsigned int* neighborY,
												 unsigned int* neighborZ,
												 unsigned int size_Mat, 
												 bool evenOrOdd);

extern "C" __global__ void QInflowScaleByPressDevice27(  doubflo* rhoBC,
														 doubflo* DD, 
														 int* k_Q, 
														 int* k_N, 
														 int kQ, 
														 doubflo om1, 
														 unsigned int* neighborX,
														 unsigned int* neighborY,
														 unsigned int* neighborZ,
														 unsigned int size_Mat, 
														 bool evenOrOdd);

extern "C" __global__ void QPressDeviceOld27(doubflo* rhoBC,
                                             doubflo* DD, 
                                             int* k_Q, 
                                             int* k_N, 
                                             int kQ, 
                                             doubflo om1, 
                                             unsigned int* neighborX,
                                             unsigned int* neighborY,
                                             unsigned int* neighborZ,
                                             unsigned int size_Mat, 
                                             bool evenOrOdd);

extern "C" __global__ void QPressDeviceIncompNEQ27( doubflo* rhoBC,
													doubflo* DD, 
													int* k_Q, 
													int* k_N, 
													int kQ, 
													doubflo om1, 
													unsigned int* neighborX,
													unsigned int* neighborY,
													unsigned int* neighborZ,
													unsigned int size_Mat, 
													bool evenOrOdd);

extern "C" __global__ void QPressDeviceNEQ27(doubflo* rhoBC,
                                             doubflo* DD, 
                                             int* k_Q, 
                                             int* k_N, 
                                             int kQ, 
                                             doubflo om1, 
                                             unsigned int* neighborX,
                                             unsigned int* neighborY,
                                             unsigned int* neighborZ,
                                             unsigned int size_Mat, 
                                             bool evenOrOdd);

extern "C" __global__ void QPressDeviceEQZ27(doubflo* rhoBC,
                                             doubflo* DD, 
                                             int* k_Q, 
                                             int* k_N, 
                                             doubflo* kTestRE, 
                                             int kQ, 
                                             doubflo om1, 
                                             unsigned int* neighborX,
                                             unsigned int* neighborY,
                                             unsigned int* neighborZ,
                                             unsigned int size_Mat, 
                                             bool evenOrOdd);

extern "C" __global__ void QPressDeviceZero27(  doubflo* DD, 
												int* k_Q, 
												unsigned int kQ, 
												unsigned int* neighborX,
												unsigned int* neighborY,
												unsigned int* neighborZ,
												unsigned int size_Mat, 
												bool evenOrOdd);

extern "C" __global__ void QPressDeviceFake27(doubflo* rhoBC,
                                             doubflo* DD, 
                                             int* k_Q, 
                                             int* k_N, 
                                             int kQ, 
                                             doubflo om1, 
                                             unsigned int* neighborX,
                                             unsigned int* neighborY,
                                             unsigned int* neighborZ,
                                             unsigned int size_Mat, 
                                             bool evenOrOdd);

extern "C" __global__ void BBDevice27(int inx,
                                     int iny,
                                     doubflo* DD, 
                                     int* k_Q, 
                                     doubflo* QQ,
                                     unsigned int sizeQ,
                                     int kQ, 
                                     doubflo om1, 
                                     unsigned int* neighborX,
                                     unsigned int* neighborY,
                                     unsigned int* neighborZ,
                                     unsigned int size_Mat, 
                                     bool evenOrOdd);

extern "C" __global__ void QPressDevice27_IntBB(doubflo* rho,
												doubflo* DD, 
												int* k_Q, 
												doubflo* QQ,
												unsigned int sizeQ,
												int kQ, 
												doubflo om1, 
												unsigned int* neighborX,
												unsigned int* neighborY,
												unsigned int* neighborZ,
												unsigned int size_Mat, 
												bool evenOrOdd);

extern "C" __global__ void PressSchlaff27(doubflo* rhoBC,
                                          doubflo* DD,
                                          doubflo* vx0,
                                          doubflo* vy0,
                                          doubflo* vz0,
                                          doubflo* deltaVz0,
                                          int* k_Q, 
                                          int* k_N, 
                                          int kQ, 
                                          doubflo om1, 
                                          unsigned int* neighborX,
                                          unsigned int* neighborY,
                                          unsigned int* neighborZ,
                                          unsigned int size_Mat, 
                                          bool evenOrOdd);

extern "C" __global__ void VelSchlaff27(  int t,
                                          doubflo* DD,
                                          doubflo* vz0,
                                          doubflo* deltaVz0,
                                          int* k_Q, 
                                          int* k_N, 
                                          int kQ, 
                                          doubflo om1, 
                                          unsigned int* neighborX,
                                          unsigned int* neighborY,
                                          unsigned int* neighborZ,
                                          unsigned int size_Mat, 
                                          bool evenOrOdd);

extern "C" __global__ void QAD7( int inx,
                                 int iny,
                                 doubflo* DD, 
                                 doubflo* DD7, 
                                 doubflo* temp,
                                 doubflo diffusivity,
                                 int* k_Q, 
                                 doubflo* QQ,
                                 unsigned int sizeQ,
                                 int kQ, 
                                 doubflo om1, 
                                 unsigned int* neighborX,
                                 unsigned int* neighborY,
                                 unsigned int* neighborZ,
                                 unsigned int size_Mat, 
                                 bool evenOrOdd);

extern "C" __global__ void QADDirichlet27(   int inx,
											 int iny,
											 doubflo* DD, 
											 doubflo* DD27, 
											 doubflo* temp, 
											 doubflo diffusivity,
											 int* k_Q, 
											 doubflo* QQ,
											 unsigned int sizeQ,
											 int kQ, 
											 doubflo om1, 
											 unsigned int* neighborX,
											 unsigned int* neighborY,
											 unsigned int* neighborZ,
											 unsigned int size_Mat, 
											 bool evenOrOdd);

extern "C" __global__ void QADBB27(  int inx,
									 int iny,
									 doubflo* DD, 
									 doubflo* DD27, 
									 doubflo* temp, 
									 doubflo diffusivity,
									 int* k_Q, 
									 doubflo* QQ,
									 unsigned int sizeQ,
									 int kQ, 
									 doubflo om1, 
									 unsigned int* neighborX,
									 unsigned int* neighborY,
									 unsigned int* neighborZ,
									 unsigned int size_Mat, 
									 bool evenOrOdd);

extern "C" __global__ void QADVel7( int inx,
                                    int iny,
                                    doubflo* DD, 
                                    doubflo* DD7, 
                                    doubflo* temp,
                                    doubflo* velo,
                                    doubflo diffusivity,
                                    int* k_Q, 
                                    doubflo* QQ,
                                    unsigned int sizeQ,
                                    int kQ, 
                                    doubflo om1, 
                                    unsigned int* neighborX,
                                    unsigned int* neighborY,
                                    unsigned int* neighborZ,
                                    unsigned int size_Mat, 
                                    bool evenOrOdd);

extern "C" __global__ void QADVel27(int inx,
                                    int iny,
                                    doubflo* DD, 
                                    doubflo* DD27, 
                                    doubflo* temp, 
                                    doubflo* velo, 
                                    doubflo diffusivity,
                                    int* k_Q, 
                                    doubflo* QQ,
                                    unsigned int sizeQ,
                                    int kQ, 
                                    doubflo om1, 
                                    unsigned int* neighborX,
                                    unsigned int* neighborY,
                                    unsigned int* neighborZ,
                                    unsigned int size_Mat, 
                                    bool evenOrOdd);

extern "C" __global__ void QADPress7(  int inx,
                                       int iny,
                                       doubflo* DD, 
                                       doubflo* DD7, 
                                       doubflo* temp,
                                       doubflo* velo,
                                       doubflo diffusivity,
                                       int* k_Q, 
                                       doubflo* QQ,
                                       unsigned int sizeQ,
                                       int kQ, 
                                       doubflo om1, 
                                       unsigned int* neighborX,
                                       unsigned int* neighborY,
                                       unsigned int* neighborZ,
                                       unsigned int size_Mat, 
                                       bool evenOrOdd);

extern "C" __global__ void QADPress27( int inx,
                                       int iny,
                                       doubflo* DD, 
                                       doubflo* DD27, 
                                       doubflo* temp, 
                                       doubflo* velo, 
                                       doubflo diffusivity,
                                       int* k_Q, 
                                       doubflo* QQ,
                                       unsigned int sizeQ,
                                       int kQ, 
                                       doubflo om1, 
                                       unsigned int* neighborX,
                                       unsigned int* neighborY,
                                       unsigned int* neighborZ,
                                       unsigned int size_Mat, 
                                       bool evenOrOdd);

extern "C" __global__ void QNoSlipADincomp7( int inx,
											 int iny,
											 doubflo* DD, 
											 doubflo* DD7, 
											 doubflo* temp,
											 doubflo diffusivity,
											 int* k_Q, 
											 doubflo* QQ,
											 unsigned int sizeQ,
											 int kQ, 
											 doubflo om1, 
											 unsigned int* neighborX,
											 unsigned int* neighborY,
											 unsigned int* neighborZ,
											 unsigned int size_Mat, 
											 bool evenOrOdd);

extern "C" __global__ void QNoSlipADincomp27(int inx,
											 int iny,
											 doubflo* DD, 
											 doubflo* DD27, 
											 doubflo* temp, 
											 doubflo diffusivity,
											 int* k_Q, 
											 doubflo* QQ,
											 unsigned int sizeQ,
											 int kQ, 
											 doubflo om1, 
											 unsigned int* neighborX,
											 unsigned int* neighborY,
											 unsigned int* neighborZ,
											 unsigned int size_Mat, 
											 bool evenOrOdd);

extern "C" __global__ void QADVeloIncomp7(  int inx,
											int iny,
											doubflo* DD, 
											doubflo* DD7, 
											doubflo* temp,
											doubflo* velo,
											doubflo diffusivity,
											int* k_Q, 
											doubflo* QQ,
											unsigned int sizeQ,
											int kQ, 
											doubflo om1, 
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat, 
											bool evenOrOdd);

extern "C" __global__ void QADVeloIncomp27( int inx,
											int iny,
											doubflo* DD, 
											doubflo* DD27, 
											doubflo* temp, 
											doubflo* velo, 
											doubflo diffusivity,
											int* k_Q, 
											doubflo* QQ,
											unsigned int sizeQ,
											int kQ, 
											doubflo om1, 
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat, 
											bool evenOrOdd);

extern "C" __global__ void QADPressIncomp7(int inx,
										   int iny,
										   doubflo* DD, 
										   doubflo* DD7, 
										   doubflo* temp,
										   doubflo* velo,
										   doubflo diffusivity,
										   int* k_Q, 
										   doubflo* QQ,
										   unsigned int sizeQ,
										   int kQ, 
										   doubflo om1, 
										   unsigned int* neighborX,
										   unsigned int* neighborY,
										   unsigned int* neighborZ,
										   unsigned int size_Mat, 
										   bool evenOrOdd);

extern "C" __global__ void QADPressIncomp27(   int inx,
											   int iny,
											   doubflo* DD, 
											   doubflo* DD27, 
											   doubflo* temp, 
											   doubflo* velo, 
											   doubflo diffusivity,
											   int* k_Q, 
											   doubflo* QQ,
											   unsigned int sizeQ,
											   int kQ, 
											   doubflo om1, 
											   unsigned int* neighborX,
											   unsigned int* neighborY,
											   unsigned int* neighborZ,
											   unsigned int size_Mat, 
											   bool evenOrOdd);

extern "C" __global__ void PropellerBC(unsigned int* neighborX,
                                       unsigned int* neighborY,
                                       unsigned int* neighborZ,
                                       doubflo* rho,
                                       doubflo* ux,
                                       doubflo* uy,
                                       doubflo* uz,
                                       int* k_Q, 
									   unsigned int size_Prop,
                                       unsigned int size_Mat,
                                       unsigned int* bcMatD,
                                       doubflo* DD,
                                       bool EvenOrOdd);



//coarse to fine
extern "C" __global__ void scaleCF27(doubflo* DC, 
                                     doubflo* DF, 
                                    unsigned int* neighborCX,
                                    unsigned int* neighborCY,
                                    unsigned int* neighborCZ,
                                    unsigned int* neighborFX,
                                    unsigned int* neighborFY,
                                    unsigned int* neighborFZ,
										       unsigned int size_MatC, 
										       unsigned int size_MatF, 
										       bool evenOrOdd,
                                     unsigned int* posCSWB, 
                                     unsigned int* posFSWB, 
                                     unsigned int kCF, 
										       doubflo omCoarse, 
										       doubflo omFine, 
										       doubflo nu, 
										       unsigned int nxC, 
										       unsigned int nyC, 
										       unsigned int nxF, 
										       unsigned int nyF);

extern "C" __global__ void scaleCFEff27(doubflo* DC, 
                                        doubflo* DF, 
                                        unsigned int* neighborCX,
                                        unsigned int* neighborCY,
                                        unsigned int* neighborCZ,
                                        unsigned int* neighborFX,
                                        unsigned int* neighborFY,
                                        unsigned int* neighborFZ,
									             unsigned int size_MatC, 
									             unsigned int size_MatF, 
									             bool evenOrOdd,
                                        unsigned int* posCSWB, 
                                        unsigned int* posFSWB, 
                                        unsigned int kCF, 
									             doubflo omCoarse, 
									             doubflo omFine, 
									             doubflo nu, 
									             unsigned int nxC, 
									             unsigned int nyC, 
									             unsigned int nxF, 
                                        unsigned int nyF,
                                        OffCF offCF);

extern "C" __global__ void scaleCFLast27( doubflo* DC, 
                                          doubflo* DF, 
                                          unsigned int* neighborCX,
                                          unsigned int* neighborCY,
                                          unsigned int* neighborCZ,
                                          unsigned int* neighborFX,
                                          unsigned int* neighborFY,
                                          unsigned int* neighborFZ,
                                          unsigned int size_MatC, 
                                          unsigned int size_MatF, 
                                          bool evenOrOdd,
                                          unsigned int* posCSWB, 
                                          unsigned int* posFSWB, 
                                          unsigned int kCF, 
                                          doubflo omCoarse, 
                                          doubflo omFine, 
                                          doubflo nu, 
                                          unsigned int nxC, 
                                          unsigned int nyC, 
                                          unsigned int nxF, 
                                          unsigned int nyF,
                                          OffCF offCF);

extern "C" __global__ void scaleCFpress27(doubflo* DC, 
                                          doubflo* DF, 
                                          unsigned int* neighborCX,
                                          unsigned int* neighborCY,
                                          unsigned int* neighborCZ,
                                          unsigned int* neighborFX,
                                          unsigned int* neighborFY,
                                          unsigned int* neighborFZ,
                                          unsigned int size_MatC, 
                                          unsigned int size_MatF, 
                                          bool evenOrOdd,
                                          unsigned int* posCSWB, 
                                          unsigned int* posFSWB, 
                                          unsigned int kCF, 
                                          doubflo omCoarse, 
                                          doubflo omFine, 
                                          doubflo nu, 
                                          unsigned int nxC, 
                                          unsigned int nyC, 
                                          unsigned int nxF, 
                                          unsigned int nyF,
                                          OffCF offCF);

extern "C" __global__ void scaleCF_Fix_27(doubflo* DC, 
                                          doubflo* DF, 
                                          unsigned int* neighborCX,
                                          unsigned int* neighborCY,
                                          unsigned int* neighborCZ,
                                          unsigned int* neighborFX,
                                          unsigned int* neighborFY,
                                          unsigned int* neighborFZ,
                                          unsigned int size_MatC, 
                                          unsigned int size_MatF, 
                                          bool evenOrOdd,
                                          unsigned int* posCSWB, 
                                          unsigned int* posFSWB, 
                                          unsigned int kCF, 
                                          doubflo omCoarse, 
                                          doubflo omFine, 
                                          doubflo nu, 
                                          unsigned int nxC, 
                                          unsigned int nyC, 
                                          unsigned int nxF, 
                                          unsigned int nyF,
                                          OffCF offCF);

extern "C" __global__ void scaleCF_Fix_comp_27(   doubflo* DC, 
												  doubflo* DF, 
												  unsigned int* neighborCX,
												  unsigned int* neighborCY,
												  unsigned int* neighborCZ,
												  unsigned int* neighborFX,
												  unsigned int* neighborFY,
												  unsigned int* neighborFZ,
												  unsigned int size_MatC, 
												  unsigned int size_MatF, 
												  bool evenOrOdd,
												  unsigned int* posCSWB, 
												  unsigned int* posFSWB, 
												  unsigned int kCF, 
												  doubflo omCoarse, 
												  doubflo omFine, 
												  doubflo nu, 
												  unsigned int nxC, 
												  unsigned int nyC, 
												  unsigned int nxF, 
												  unsigned int nyF,
												  OffCF offCF);

extern "C" __global__ void scaleCF_0817_comp_27(  doubflo* DC, 
												  doubflo* DF, 
												  unsigned int* neighborCX,
												  unsigned int* neighborCY,
												  unsigned int* neighborCZ,
												  unsigned int* neighborFX,
												  unsigned int* neighborFY,
												  unsigned int* neighborFZ,
												  unsigned int size_MatC, 
												  unsigned int size_MatF, 
												  bool evenOrOdd,
												  unsigned int* posCSWB, 
												  unsigned int* posFSWB, 
												  unsigned int kCF, 
												  doubflo omCoarse, 
												  doubflo omFine, 
												  doubflo nu, 
												  unsigned int nxC, 
												  unsigned int nyC, 
												  unsigned int nxF, 
												  unsigned int nyF,
												  OffCF offCF);

extern "C" __global__ void scaleCF_staggered_time_comp_27(doubflo* DC, 
														  doubflo* DF, 
														  unsigned int* neighborCX,
														  unsigned int* neighborCY,
														  unsigned int* neighborCZ,
														  unsigned int* neighborFX,
														  unsigned int* neighborFY,
														  unsigned int* neighborFZ,
														  unsigned int size_MatC, 
														  unsigned int size_MatF, 
														  bool evenOrOdd,
														  unsigned int* posCSWB, 
														  unsigned int* posFSWB, 
														  unsigned int kCF, 
														  doubflo omCoarse, 
														  doubflo omFine, 
														  doubflo nu, 
														  unsigned int nxC, 
														  unsigned int nyC, 
														  unsigned int nxF, 
														  unsigned int nyF,
														  OffCF offCF);

extern "C" __global__ void scaleCF_RhoSq_comp_27( doubflo* DC, 
												  doubflo* DF, 
												  unsigned int* neighborCX,
												  unsigned int* neighborCY,
												  unsigned int* neighborCZ,
												  unsigned int* neighborFX,
												  unsigned int* neighborFY,
												  unsigned int* neighborFZ,
												  unsigned int size_MatC, 
												  unsigned int size_MatF, 
												  bool evenOrOdd,
												  unsigned int* posCSWB, 
												  unsigned int* posFSWB, 
												  unsigned int kCF, 
												  doubflo omCoarse, 
												  doubflo omFine, 
												  doubflo nu, 
												  unsigned int nxC, 
												  unsigned int nyC, 
												  unsigned int nxF, 
												  unsigned int nyF,
												  OffCF offCF);

extern "C" __global__ void scaleCF_RhoSq_3rdMom_comp_27(doubflo* DC, 
														doubflo* DF, 
														unsigned int* neighborCX,
														unsigned int* neighborCY,
														unsigned int* neighborCZ,
														unsigned int* neighborFX,
														unsigned int* neighborFY,
														unsigned int* neighborFZ,
														unsigned int size_MatC, 
														unsigned int size_MatF, 
														bool evenOrOdd,
														unsigned int* posCSWB, 
														unsigned int* posFSWB, 
														unsigned int kCF, 
														doubflo omCoarse, 
														doubflo omFine, 
														doubflo nu, 
														unsigned int nxC, 
														unsigned int nyC, 
														unsigned int nxF, 
														unsigned int nyF,
														OffCF offCF);

extern "C" __global__ void scaleCF_AA2016_comp_27(doubflo* DC, 
												  doubflo* DF, 
												  unsigned int* neighborCX,
												  unsigned int* neighborCY,
												  unsigned int* neighborCZ,
												  unsigned int* neighborFX,
												  unsigned int* neighborFY,
												  unsigned int* neighborFZ,
												  unsigned int size_MatC, 
												  unsigned int size_MatF, 
												  bool evenOrOdd,
												  unsigned int* posCSWB, 
												  unsigned int* posFSWB, 
												  unsigned int kCF, 
												  doubflo omCoarse, 
												  doubflo omFine, 
												  doubflo nu, 
												  unsigned int nxC, 
												  unsigned int nyC, 
												  unsigned int nxF, 
												  unsigned int nyF,
												  OffCF offCF);

extern "C" __global__ void scaleCF_NSPress_27(doubflo* DC, 
											  doubflo* DF, 
											  unsigned int* neighborCX,
											  unsigned int* neighborCY,
											  unsigned int* neighborCZ,
											  unsigned int* neighborFX,
											  unsigned int* neighborFY,
											  unsigned int* neighborFZ,
											  unsigned int size_MatC, 
											  unsigned int size_MatF, 
											  bool evenOrOdd,
											  unsigned int* posCSWB, 
											  unsigned int* posFSWB, 
											  unsigned int kCF, 
											  doubflo omCoarse, 
											  doubflo omFine, 
											  doubflo nu, 
											  unsigned int nxC, 
											  unsigned int nyC, 
											  unsigned int nxF, 
											  unsigned int nyF,
											  OffCF offCF);

extern "C" __global__ void scaleCFThSMG7( doubflo* DC, 
                                          doubflo* DF,
                                          doubflo* DD7C, 
                                          doubflo* DD7F, 
                                          unsigned int* neighborCX,
                                          unsigned int* neighborCY,
                                          unsigned int* neighborCZ,
                                          unsigned int* neighborFX,
                                          unsigned int* neighborFY,
                                          unsigned int* neighborFZ,
                                          unsigned int size_MatC, 
                                          unsigned int size_MatF, 
                                          bool evenOrOdd,
                                          unsigned int* posCSWB, 
                                          unsigned int* posFSWB, 
                                          unsigned int kCF, 
                                          doubflo nu,
                                          doubflo diffusivity_fine,
                                          OffCF offCF);

extern "C" __global__ void scaleCFThS7(doubflo* DC, 
                                       doubflo* DF,
                                       doubflo* DD7C, 
                                       doubflo* DD7F, 
                                       unsigned int* neighborCX,
                                       unsigned int* neighborCY,
                                       unsigned int* neighborCZ,
                                       unsigned int* neighborFX,
                                       unsigned int* neighborFY,
                                       unsigned int* neighborFZ,
                                       unsigned int size_MatC, 
                                       unsigned int size_MatF, 
                                       bool evenOrOdd,
                                       unsigned int* posCSWB, 
                                       unsigned int* posFSWB, 
                                       unsigned int kCF, 
                                       doubflo nu,
                                       doubflo diffusivity_fine);

extern "C" __global__ void scaleCFThS27(doubflo* DC, 
                                        doubflo* DF,
                                        doubflo* DD27C, 
                                        doubflo* DD27F, 
                                        unsigned int* neighborCX,
                                        unsigned int* neighborCY,
                                        unsigned int* neighborCZ,
                                        unsigned int* neighborFX,
                                        unsigned int* neighborFY,
                                        unsigned int* neighborFZ,
                                        unsigned int size_MatC, 
                                        unsigned int size_MatF, 
                                        bool evenOrOdd,
                                        unsigned int* posCSWB, 
                                        unsigned int* posFSWB, 
                                        unsigned int kCF, 
                                        doubflo nu,
                                        doubflo diffusivity_fine,
										OffCF offCF);

//fine to coarse 
extern "C" __global__ void scaleFC27(doubflo* DC, 
                                     doubflo* DF, 
                                    unsigned int* neighborCX,
                                    unsigned int* neighborCY,
                                    unsigned int* neighborCZ,
                                    unsigned int* neighborFX,
                                    unsigned int* neighborFY,
                                    unsigned int* neighborFZ,
										       unsigned int size_MatC, 
										       unsigned int size_MatF, 
										       bool evenOrOdd,
                                     unsigned int* posC, 
                                     unsigned int* posFSWB, 
                                     unsigned int kFC, 
										       doubflo omCoarse, 
										       doubflo omFine, 
										       doubflo nu, 
										       unsigned int nxC, 
										       unsigned int nyC, 
										       unsigned int nxF, 
                                     unsigned int nyF);

extern "C" __global__ void scaleFCEff27(doubflo* DC, 
                                        doubflo* DF, 
                                        unsigned int* neighborCX,
                                        unsigned int* neighborCY,
                                        unsigned int* neighborCZ,
                                        unsigned int* neighborFX,
                                        unsigned int* neighborFY,
                                        unsigned int* neighborFZ,
                                        unsigned int size_MatC, 
                                        unsigned int size_MatF, 
                                        bool evenOrOdd,
                                        unsigned int* posC, 
                                        unsigned int* posFSWB, 
                                        unsigned int kFC, 
                                        doubflo omCoarse, 
                                        doubflo omFine, 
                                        doubflo nu, 
                                        unsigned int nxC, 
                                        unsigned int nyC, 
                                        unsigned int nxF, 
                                        unsigned int nyF,
                                        OffFC offFC);

extern "C" __global__ void scaleFCLast27( doubflo* DC, 
                                          doubflo* DF, 
                                          unsigned int* neighborCX,
                                          unsigned int* neighborCY,
                                          unsigned int* neighborCZ,
                                          unsigned int* neighborFX,
                                          unsigned int* neighborFY,
                                          unsigned int* neighborFZ,
                                          unsigned int size_MatC, 
                                          unsigned int size_MatF, 
                                          bool evenOrOdd,
                                          unsigned int* posC, 
                                          unsigned int* posFSWB, 
                                          unsigned int kFC, 
                                          doubflo omCoarse, 
                                          doubflo omFine, 
                                          doubflo nu, 
                                          unsigned int nxC, 
                                          unsigned int nyC, 
                                          unsigned int nxF, 
                                          unsigned int nyF,
                                          OffFC offFC);

extern "C" __global__ void scaleFCpress27( doubflo* DC, 
                                          doubflo* DF, 
                                          unsigned int* neighborCX,
                                          unsigned int* neighborCY,
                                          unsigned int* neighborCZ,
                                          unsigned int* neighborFX,
                                          unsigned int* neighborFY,
                                          unsigned int* neighborFZ,
                                          unsigned int size_MatC, 
                                          unsigned int size_MatF, 
                                          bool evenOrOdd,
                                          unsigned int* posC, 
                                          unsigned int* posFSWB, 
                                          unsigned int kFC, 
                                          doubflo omCoarse, 
                                          doubflo omFine, 
                                          doubflo nu, 
                                          unsigned int nxC, 
                                          unsigned int nyC, 
                                          unsigned int nxF, 
                                          unsigned int nyF,
                                          OffFC offFC);

extern "C" __global__ void scaleFC_Fix_27( doubflo* DC, 
                                          doubflo* DF, 
                                          unsigned int* neighborCX,
                                          unsigned int* neighborCY,
                                          unsigned int* neighborCZ,
                                          unsigned int* neighborFX,
                                          unsigned int* neighborFY,
                                          unsigned int* neighborFZ,
                                          unsigned int size_MatC, 
                                          unsigned int size_MatF, 
                                          bool evenOrOdd,
                                          unsigned int* posC, 
                                          unsigned int* posFSWB, 
                                          unsigned int kFC, 
                                          doubflo omCoarse, 
                                          doubflo omFine, 
                                          doubflo nu, 
                                          unsigned int nxC, 
                                          unsigned int nyC, 
                                          unsigned int nxF, 
                                          unsigned int nyF,
                                          OffFC offFC);

extern "C" __global__ void scaleFC_Fix_comp_27(   doubflo* DC, 
												  doubflo* DF, 
												  unsigned int* neighborCX,
												  unsigned int* neighborCY,
												  unsigned int* neighborCZ,
												  unsigned int* neighborFX,
												  unsigned int* neighborFY,
												  unsigned int* neighborFZ,
												  unsigned int size_MatC, 
												  unsigned int size_MatF, 
												  bool evenOrOdd,
												  unsigned int* posC, 
												  unsigned int* posFSWB, 
												  unsigned int kFC, 
												  doubflo omCoarse, 
												  doubflo omFine, 
												  doubflo nu, 
												  unsigned int nxC, 
												  unsigned int nyC, 
												  unsigned int nxF, 
												  unsigned int nyF,
												  OffFC offFC);

extern "C" __global__ void scaleFC_0817_comp_27(  doubflo* DC, 
												  doubflo* DF, 
												  unsigned int* neighborCX,
												  unsigned int* neighborCY,
												  unsigned int* neighborCZ,
												  unsigned int* neighborFX,
												  unsigned int* neighborFY,
												  unsigned int* neighborFZ,
												  unsigned int size_MatC, 
												  unsigned int size_MatF, 
												  bool evenOrOdd,
												  unsigned int* posC, 
												  unsigned int* posFSWB, 
												  unsigned int kFC, 
												  doubflo omCoarse, 
												  doubflo omFine, 
												  doubflo nu, 
												  unsigned int nxC, 
												  unsigned int nyC, 
												  unsigned int nxF, 
												  unsigned int nyF,
												  OffFC offFC);

extern "C" __global__ void scaleFC_staggered_time_comp_27(doubflo* DC, 
														  doubflo* DF, 
														  unsigned int* neighborCX,
														  unsigned int* neighborCY,
														  unsigned int* neighborCZ,
														  unsigned int* neighborFX,
														  unsigned int* neighborFY,
														  unsigned int* neighborFZ,
														  unsigned int size_MatC, 
														  unsigned int size_MatF, 
														  bool evenOrOdd,
														  unsigned int* posC, 
														  unsigned int* posFSWB, 
														  unsigned int kFC, 
														  doubflo omCoarse, 
														  doubflo omFine, 
														  doubflo nu, 
														  unsigned int nxC, 
														  unsigned int nyC, 
														  unsigned int nxF, 
														  unsigned int nyF,
														  OffFC offFC);

extern "C" __global__ void scaleFC_RhoSq_comp_27( doubflo* DC, 
												  doubflo* DF, 
												  unsigned int* neighborCX,
												  unsigned int* neighborCY,
												  unsigned int* neighborCZ,
												  unsigned int* neighborFX,
												  unsigned int* neighborFY,
												  unsigned int* neighborFZ,
												  unsigned int size_MatC, 
												  unsigned int size_MatF, 
												  bool evenOrOdd,
												  unsigned int* posC, 
												  unsigned int* posFSWB, 
												  unsigned int kFC, 
												  doubflo omCoarse, 
												  doubflo omFine, 
												  doubflo nu, 
												  unsigned int nxC, 
												  unsigned int nyC, 
												  unsigned int nxF, 
												  unsigned int nyF,
												  OffFC offFC);

extern "C" __global__ void scaleFC_RhoSq_3rdMom_comp_27(doubflo* DC, 
														doubflo* DF, 
														unsigned int* neighborCX,
														unsigned int* neighborCY,
														unsigned int* neighborCZ,
														unsigned int* neighborFX,
														unsigned int* neighborFY,
														unsigned int* neighborFZ,
														unsigned int size_MatC, 
														unsigned int size_MatF, 
														bool evenOrOdd,
														unsigned int* posC, 
														unsigned int* posFSWB, 
														unsigned int kFC, 
														doubflo omCoarse, 
														doubflo omFine, 
														doubflo nu, 
														unsigned int nxC, 
														unsigned int nyC, 
														unsigned int nxF, 
														unsigned int nyF,
														OffFC offFC);

extern "C" __global__ void scaleFC_AA2016_comp_27(doubflo* DC, 
												  doubflo* DF, 
												  unsigned int* neighborCX,
												  unsigned int* neighborCY,
												  unsigned int* neighborCZ,
												  unsigned int* neighborFX,
												  unsigned int* neighborFY,
												  unsigned int* neighborFZ,
												  unsigned int size_MatC, 
												  unsigned int size_MatF, 
												  bool evenOrOdd,
												  unsigned int* posC, 
												  unsigned int* posFSWB, 
												  unsigned int kFC, 
												  doubflo omCoarse, 
												  doubflo omFine, 
												  doubflo nu, 
												  unsigned int nxC, 
												  unsigned int nyC, 
												  unsigned int nxF, 
												  unsigned int nyF,
												  OffFC offFC);

extern "C" __global__ void scaleFC_NSPress_27(doubflo* DC, 
											  doubflo* DF, 
											  unsigned int* neighborCX,
											  unsigned int* neighborCY,
											  unsigned int* neighborCZ,
											  unsigned int* neighborFX,
											  unsigned int* neighborFY,
											  unsigned int* neighborFZ,
											  unsigned int size_MatC, 
											  unsigned int size_MatF, 
											  bool evenOrOdd,
											  unsigned int* posC, 
											  unsigned int* posFSWB, 
											  unsigned int kFC, 
											  doubflo omCoarse, 
											  doubflo omFine, 
											  doubflo nu, 
											  unsigned int nxC, 
											  unsigned int nyC, 
											  unsigned int nxF, 
											  unsigned int nyF,
											  OffFC offFC);

extern "C" __global__ void scaleFCThSMG7( doubflo* DC, 
                                          doubflo* DF, 
                                          doubflo* DD7C, 
                                          doubflo* DD7F, 
                                          unsigned int* neighborCX,
                                          unsigned int* neighborCY,
                                          unsigned int* neighborCZ,
                                          unsigned int* neighborFX,
                                          unsigned int* neighborFY,
                                          unsigned int* neighborFZ,
                                          unsigned int size_MatC, 
                                          unsigned int size_MatF, 
                                          bool evenOrOdd,
                                          unsigned int* posC, 
                                          unsigned int* posFSWB, 
                                          unsigned int kFC, 
                                          doubflo nu,
                                          doubflo diffusivity_coarse,
                                          OffFC offFC);

extern "C" __global__ void scaleFCThS7(doubflo* DC, 
                                       doubflo* DF, 
                                       doubflo* DD7C, 
                                       doubflo* DD7F, 
                                       unsigned int* neighborCX,
                                       unsigned int* neighborCY,
                                       unsigned int* neighborCZ,
                                       unsigned int* neighborFX,
                                       unsigned int* neighborFY,
                                       unsigned int* neighborFZ,
                                       unsigned int size_MatC, 
                                       unsigned int size_MatF, 
                                       bool evenOrOdd,
                                       unsigned int* posC, 
                                       unsigned int* posFSWB, 
                                       unsigned int kFC, 
                                       doubflo nu,
                                       doubflo diffusivity_coarse);

extern "C" __global__ void scaleFCThS27(  doubflo* DC, 
                                          doubflo* DF, 
                                          doubflo* DD27C, 
                                          doubflo* DD27F, 
                                          unsigned int* neighborCX,
                                          unsigned int* neighborCY,
                                          unsigned int* neighborCZ,
                                          unsigned int* neighborFX,
                                          unsigned int* neighborFY,
                                          unsigned int* neighborFZ,
                                          unsigned int size_MatC, 
                                          unsigned int size_MatF, 
                                          bool evenOrOdd,
                                          unsigned int* posC, 
                                          unsigned int* posFSWB, 
                                          unsigned int kFC, 
                                          doubflo nu,
                                          doubflo diffusivity_coarse,
										  OffFC offFC);

extern "C" __global__ void DragLiftPost27(  doubflo* DD, 
											int* k_Q, 
											doubflo* QQ,
											int kQ, 
											double *DragX,
											double *DragY,
											double *DragZ,
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat, 
											bool evenOrOdd);

extern "C" __global__ void DragLiftPre27(   doubflo* DD, 
											int* k_Q, 
											doubflo* QQ,
											int kQ, 
											double *DragX,
											double *DragY,
											double *DragZ,
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat, 
											bool evenOrOdd);

extern "C" __global__ void CalcCP27(doubflo* DD, 
									int* cpIndex, 
									int nonCp, 
									double *cpPress,
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int size_Mat, 
									bool evenOrOdd);

extern "C" __global__ void getSendFsPre27(doubflo* DD,
										  doubflo* bufferFs,
										  int* sendIndex,
                                          int buffmax,
                                          unsigned int* neighborX,
                                          unsigned int* neighborY,
                                          unsigned int* neighborZ,
                                          unsigned int size_Mat, 
                                          bool evenOrOdd);

extern "C" __global__ void getSendFsPost27(doubflo* DD,
										   doubflo* bufferFs,
										   int* sendIndex,
                                           int buffmax,
                                           unsigned int* neighborX,
                                           unsigned int* neighborY,
                                           unsigned int* neighborZ,
                                           unsigned int size_Mat, 
                                           bool evenOrOdd);

extern "C" __global__ void setRecvFsPre27(doubflo* DD,
										  doubflo* bufferFs,
										  int* recvIndex,
                                          int buffmax,
                                          unsigned int* neighborX,
                                          unsigned int* neighborY,
                                          unsigned int* neighborZ,
                                          unsigned int size_Mat, 
                                          bool evenOrOdd);

extern "C" __global__ void setRecvFsPost27(doubflo* DD,
										   doubflo* bufferFs,
										   int* recvIndex,
                                           int buffmax,
                                           unsigned int* neighborX,
                                           unsigned int* neighborY,
                                           unsigned int* neighborZ,
                                           unsigned int size_Mat, 
                                           bool evenOrOdd);

extern "C" __global__ void WallFunction27(  int inx,
											int iny,
											doubflo* vx,
											doubflo* vy,
											doubflo* vz,
											doubflo* DD, 
											int* k_Q, 
											doubflo* QQ,
											unsigned int sizeQ,
											int kQ, 
											doubflo om1, 
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat, 
											bool evenOrOdd);

extern "C" __global__ void LBSetOutputWallVelocitySP27( doubflo* vxD,
														doubflo* vyD,
														doubflo* vzD,
														doubflo* vxWall,
														doubflo* vyWall,
														doubflo* vzWall,
														int numberOfWallNodes, 
														int* kWallNodes, 
														doubflo* rhoD,
														doubflo* pressD,
														unsigned int* geoD,
														unsigned int* neighborX,
														unsigned int* neighborY,
														unsigned int* neighborZ,
														unsigned int size_Mat,
														doubflo* DD,
														bool evenOrOdd);

extern "C" __global__ void GetVeloforForcing27( doubflo* DD, 
												int* bcIndex, 
												int nonAtBC, 
												doubflo* Vx,
												doubflo* Vy,
												doubflo* Vz,
												unsigned int* neighborX,
												unsigned int* neighborY,
												unsigned int* neighborZ,
												unsigned int size_Mat, 
												bool evenOrOdd);

extern "C" __global__ void InitParticles( doubflo* coordX,
										  doubflo* coordY,
										  doubflo* coordZ, 
										  doubflo* coordParticleXlocal,
										  doubflo* coordParticleYlocal,
										  doubflo* coordParticleZlocal, 
										  doubflo* coordParticleXglobal,
										  doubflo* coordParticleYglobal,
										  doubflo* coordParticleZglobal,
										  doubflo* veloParticleX,
										  doubflo* veloParticleY,
										  doubflo* veloParticleZ,
										  doubflo* randArray,
										  unsigned int* particleID,
										  unsigned int* cellBaseID,
										  unsigned int* bcMatD,
										  unsigned int* neighborX,
										  unsigned int* neighborY,
										  unsigned int* neighborZ,
										  unsigned int* neighborWSB,
										  int level,
									      unsigned int numberOfParticles, 
										  unsigned int size_Mat);

extern "C" __global__ void MoveParticles( doubflo* coordX,
										  doubflo* coordY,
										  doubflo* coordZ, 
										  doubflo* coordParticleXlocal,
										  doubflo* coordParticleYlocal,
										  doubflo* coordParticleZlocal,
										  doubflo* coordParticleXglobal,
										  doubflo* coordParticleYglobal,
										  doubflo* coordParticleZglobal,
										  doubflo* veloParticleX,
										  doubflo* veloParticleY,
										  doubflo* veloParticleZ,
										  doubflo* DD,
										  doubflo  omega,
										  unsigned int* particleID,
										  unsigned int* cellBaseID,
										  unsigned int* bcMatD,
										  unsigned int* neighborX,
										  unsigned int* neighborY,
										  unsigned int* neighborZ,
										  unsigned int* neighborWSB,
										  int level,
										  unsigned int timestep, 
										  unsigned int numberOfTimesteps, 
									      unsigned int numberOfParticles, 
										  unsigned int size_Mat,
										  bool evenOrOdd);

extern "C" __global__ void MoveParticlesWithoutBCs(   doubflo* coordX,
													  doubflo* coordY,
													  doubflo* coordZ, 
													  doubflo* coordParticleXlocal,
													  doubflo* coordParticleYlocal,
													  doubflo* coordParticleZlocal,
													  doubflo* coordParticleXglobal,
													  doubflo* coordParticleYglobal,
													  doubflo* coordParticleZglobal,
													  doubflo* veloParticleX,
													  doubflo* veloParticleY,
													  doubflo* veloParticleZ,
													  doubflo* DD,
													  doubflo  omega,
													  unsigned int* particleID,
													  unsigned int* cellBaseID,
													  unsigned int* bcMatD,
													  unsigned int* neighborX,
													  unsigned int* neighborY,
													  unsigned int* neighborZ,
													  unsigned int* neighborWSB,
													  int level,
													  unsigned int timestep, 
													  unsigned int numberOfTimesteps, 
													  unsigned int numberOfParticles, 
													  unsigned int size_Mat,
													  bool evenOrOdd);

extern "C" __global__ void initRandom(curandState* state);

extern "C" __global__ void generateRandomValues(curandState* state, 
												doubflo* randArray);


#endif
							 