//random numbers
#include <curand.h>
#include <curand_kernel.h>

extern "C" int devCheck(  int gpudevice);

//////////////////////////////////////////////////////////////////////////
//Kernel
//////////////////////////////////////////////////////////////////////////
extern "C" void KernelCas27(unsigned int grid_nx, 
                            unsigned int grid_ny, 
                            unsigned int grid_nz, 
                            doubflo s9,
                            unsigned int* bcMatD,
                            unsigned int* neighborX,
                            unsigned int* neighborY,
                            unsigned int* neighborZ,
                            doubflo* DD,
                            int size_Mat,
                            bool EvenOrOdd);

extern "C" void KernelCasSP27(unsigned int numberOfThreads, 
                              doubflo s9,
                              unsigned int* bcMatD,
                              unsigned int* neighborX,
                              unsigned int* neighborY,
                              unsigned int* neighborZ,
                              doubflo* DD,
                              int size_Mat,
                              bool EvenOrOdd);

extern "C" void KernelCasSPMS27(unsigned int numberOfThreads, 
                                doubflo s9,
                                unsigned int* bcMatD,
                                unsigned int* neighborX,
                                unsigned int* neighborY,
                                unsigned int* neighborZ,
                                doubflo* DD,
                                int size_Mat,
                                bool EvenOrOdd);

extern "C" void KernelCasSPMSOHM27( unsigned int numberOfThreads, 
                                   doubflo s9,
                                   unsigned int* bcMatD,
                                   unsigned int* neighborX,
                                   unsigned int* neighborY,
                                   unsigned int* neighborZ,
                                   doubflo* DD,
                                   int size_Mat,
                                   bool EvenOrOdd);

extern "C" void KernelCasKumSP27(unsigned int numberOfThreads, 
								 doubflo s9,
								 unsigned int* bcMatD,
								 unsigned int* neighborX,
								 unsigned int* neighborY,
								 unsigned int* neighborZ,
								 doubflo* DD,
								 int size_Mat,
								 bool EvenOrOdd);

extern "C" void KernelBGKPlusSP27(unsigned int numberOfThreads, 
								  doubflo s9,
								  unsigned int* bcMatD,
								  unsigned int* neighborX,
								  unsigned int* neighborY,
								  unsigned int* neighborZ,
								  doubflo* DD,
								  int size_Mat,
								  bool EvenOrOdd);

extern "C" void KernelBGKPlusCompSP27(unsigned int numberOfThreads, 
									  doubflo s9,
									  unsigned int* bcMatD,
									  unsigned int* neighborX,
									  unsigned int* neighborY,
									  unsigned int* neighborZ,
									  doubflo* DD,
									  int size_Mat,
									  bool EvenOrOdd);

extern "C" void KernelBGKCompSP27(unsigned int numberOfThreads, 
								  doubflo s9,
								  unsigned int* bcMatD,
								  unsigned int* neighborX,
								  unsigned int* neighborY,
								  unsigned int* neighborZ,
								  doubflo* DD,
								  int size_Mat,
								  bool EvenOrOdd);

extern "C" void KernelBGKSP27(unsigned int numberOfThreads, 
							  doubflo s9,
							  unsigned int* bcMatD,
							  unsigned int* neighborX,
							  unsigned int* neighborY,
							  unsigned int* neighborZ,
							  doubflo* DD,
							  int size_Mat,
							  bool EvenOrOdd);

extern "C" void KernelMRTSP27(unsigned int numberOfThreads, 
							  doubflo s9,
							  unsigned int* bcMatD,
							  unsigned int* neighborX,
							  unsigned int* neighborY,
							  unsigned int* neighborZ,
							  doubflo* DD,
							  int size_Mat,
							  bool EvenOrOdd);

extern "C" void KernelMRTCompSP27(unsigned int numberOfThreads, 
								  doubflo s9,
								  unsigned int* bcMatD,
								  unsigned int* neighborX,
								  unsigned int* neighborY,
								  unsigned int* neighborZ,
								  doubflo* DD,
								  int size_Mat,
								  bool EvenOrOdd);

extern "C" void KernelCumulantD3Q27All4(unsigned int numberOfThreads,
									    doubflo s9,
									    unsigned int* bcMatD,
									    unsigned int* neighborX,
									    unsigned int* neighborY,
									    unsigned int* neighborZ,
									    doubflo* DD,
									    int size_Mat,
									    int level,
									    doubflo* forces,
									    bool EvenOrOdd);

extern "C" void KernelCumulantD3Q27F3(unsigned int numberOfThreads,
									  doubflo s9,
									  unsigned int* bcMatD,
									  unsigned int* neighborX,
									  unsigned int* neighborY,
									  unsigned int* neighborZ,
									  doubflo* DD,
									  doubflo* F3,
									  int size_Mat,
									  int level,
									  doubflo* forces,
									  bool EvenOrOdd);

extern "C" void KernelKumAA2016CompBulkSP27(unsigned int numberOfThreads, 
											doubflo s9,
											unsigned int* bcMatD,
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											doubflo* DD,
											int size_Mat,
											int size_Array,
											int level,
											doubflo* forces,
											bool EvenOrOdd);

extern "C" void KernelKumAA2016CompSP27(unsigned int numberOfThreads, 
										doubflo s9,
										unsigned int* bcMatD,
										unsigned int* neighborX,
										unsigned int* neighborY,
										unsigned int* neighborZ,
										doubflo* DD,
										int size_Mat,
										int level,
										doubflo* forces,
										bool EvenOrOdd);

extern "C" void KernelKumNewCompSpongeSP27(unsigned int numberOfThreads, 
										   doubflo s9,
										   unsigned int* bcMatD,
										   unsigned int* neighborX,
										   unsigned int* neighborY,
										   unsigned int* neighborZ,
										   doubflo* coordX,
										   doubflo* coordY,
										   doubflo* coordZ,
										   doubflo* DD,
										   int size_Mat,
										   bool EvenOrOdd);

extern "C" void KernelKum1hSP27(    unsigned int numberOfThreads, 
									doubflo omega,
									doubflo deltaPhi,
									doubflo angularVelocity,
									unsigned int* bcMatD,
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									doubflo* coordX,
									doubflo* coordY,
									doubflo* coordZ,
									doubflo* DDStart,
									int size_Mat,
									bool EvenOrOdd);

extern "C" void KernelCascadeSP27(unsigned int numberOfThreads, 
								  doubflo s9,
								  unsigned int* bcMatD,
								  unsigned int* neighborX,
								  unsigned int* neighborY,
								  unsigned int* neighborZ,
								  doubflo* DD,
								  int size_Mat,
								  bool EvenOrOdd);

extern "C" void KernelCascadeCompSP27(  unsigned int numberOfThreads, 
										doubflo s9,
										unsigned int* bcMatD,
										unsigned int* neighborX,
										unsigned int* neighborY,
										unsigned int* neighborZ,
										doubflo* DD,
										int size_Mat,
										bool EvenOrOdd);

extern "C" void KernelKumNewSP27(   unsigned int numberOfThreads, 
									doubflo s9,
									unsigned int* bcMatD,
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									doubflo* DD,
									int size_Mat,
									bool EvenOrOdd);

extern "C" void KernelKumNewCompBulkSP27(   unsigned int numberOfThreads, 
											doubflo s9,
											unsigned int* bcMatD,
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											doubflo* DD,
											int size_Mat,
											int level,
											doubflo* forces,
											bool EvenOrOdd);

extern "C" void KernelKumNewCompSP27(   unsigned int numberOfThreads, 
										doubflo s9,
										unsigned int* bcMatD,
										unsigned int* neighborX,
										unsigned int* neighborY,
										unsigned int* neighborZ,
										doubflo* DD,
										int size_Mat,
										int size_Array,
										int level,
										doubflo* forces,
										bool EvenOrOdd);

extern "C" void KernelKumIsoTestSP27(unsigned int numberOfThreads, 
									 doubflo s9,
									 unsigned int* bcMatD,
									 unsigned int* neighborX,
									 unsigned int* neighborY,
									 unsigned int* neighborZ,
									 doubflo* DD,
									 doubflo* dxxUx,
									 doubflo* dyyUy,
									 doubflo* dzzUz,
									 int size_Mat,
									 bool EvenOrOdd);

extern "C" void KernelKumCompSP27(  unsigned int numberOfThreads, 
									doubflo s9,
									unsigned int* bcMatD,
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									doubflo* DD,
									int size_Mat,
									bool EvenOrOdd);

extern "C" void KernelWaleCumOneCompSP27(unsigned int numberOfThreads,
										 doubflo s9,
										 unsigned int* bcMatD,
										 unsigned int* neighborX,
										 unsigned int* neighborY,
										 unsigned int* neighborZ,
										 unsigned int* neighborWSB,
										 doubflo* veloX,
										 doubflo* veloY,
										 doubflo* veloZ,
										 doubflo* DD,
										 doubflo* turbulentViscosity,
										 int size_Mat,
										 int size_Array,
										 int level,
										 doubflo* forces,
										 bool EvenOrOdd);

extern "C" void KernelWaleCumAA2016CompSP27( unsigned int numberOfThreads,
											 doubflo s9,
											 unsigned int* bcMatD,
											 unsigned int* neighborX,
											 unsigned int* neighborY,
											 unsigned int* neighborZ,
											 unsigned int* neighborWSB,
											 doubflo* veloX,
											 doubflo* veloY,
											 doubflo* veloZ,
											 doubflo* DD,
											 doubflo* turbulentViscosity,
											 int size_Mat,
											 int size_Array,
											 int level,
											 doubflo* forces,
											 bool EvenOrOdd);

extern "C" void KernelPMCumOneCompSP27(unsigned int numberOfThreads, 
									   doubflo omega,
									   unsigned int* bcMatD,
									   unsigned int* neighborX,
									   unsigned int* neighborY,
									   unsigned int* neighborZ,
									   doubflo* DD,
									   int size_Mat,
									   int level,
									   doubflo* forces,
									   doubflo porosity,
									   doubflo darcy,
									   doubflo forchheimer,
									   unsigned int porousMedia,
									   bool EvenOrOdd);

extern "C" void KernelThS7(unsigned int numberOfThreads, 
                           doubflo diffusivity,
                           unsigned int* bcMatD,
                           unsigned int* neighborX,
                           unsigned int* neighborY,
                           unsigned int* neighborZ,
                           doubflo* DD,
                           doubflo* DD7,
                           int size_Mat,
                           bool EvenOrOdd);

extern "C" void KernelThS27(unsigned int numberOfThreads, 
                            doubflo diffusivity,
                            unsigned int* bcMatD,
                            unsigned int* neighborX,
                            unsigned int* neighborY,
                            unsigned int* neighborZ,
                            doubflo* DD,
                            doubflo* DD7,
                            int size_Mat,
                            bool EvenOrOdd);

extern "C" void KernelADincomp7(   unsigned int numberOfThreads, 
								   doubflo diffusivity,
								   unsigned int* bcMatD,
								   unsigned int* neighborX,
								   unsigned int* neighborY,
								   unsigned int* neighborZ,
								   doubflo* DD,
								   doubflo* DD7,
								   int size_Mat,
								   bool EvenOrOdd);

extern "C" void KernelADincomp27(   unsigned int numberOfThreads, 
									doubflo diffusivity,
									unsigned int* bcMatD,
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									doubflo* DD,
									doubflo* DD7,
									int size_Mat,
									bool EvenOrOdd);

extern "C" void Init27(int myid,
                       int numprocs,
                       doubflo u0,
                       unsigned int* geoD,
                       unsigned int* neighborX,
                       unsigned int* neighborY,
                       unsigned int* neighborZ,
                       doubflo* vParab,
                       unsigned int size_Mat,
                       unsigned int grid_nx, 
                       unsigned int grid_ny, 
                       unsigned int grid_nz, 
                       doubflo* DD,
                       int level,
                       int maxlevel);

extern "C" void InitF3(     unsigned int numberOfThreads,
                            unsigned int* neighborX,
                            unsigned int* neighborY,
                            unsigned int* neighborZ,
                            unsigned int* geoD,
                            doubflo* rho,
                            doubflo* ux,
                            doubflo* uy,
                            doubflo* uz,
                            unsigned int size_Mat,
                            doubflo* G6,
                            bool EvenOrOdd);

extern "C" void InitSP27(unsigned int numberOfThreads,
                         unsigned int* neighborX,
                         unsigned int* neighborY,
                         unsigned int* neighborZ,
                         unsigned int* geoD,
                         doubflo* rho,
                         doubflo* ux,
                         doubflo* uy,
                         doubflo* uz,
                         unsigned int size_Mat,
                         doubflo* DD,
                         bool EvenOrOdd);

extern "C" void InitCompSP27(unsigned int numberOfThreads,
							 unsigned int* neighborX,
							 unsigned int* neighborY,
							 unsigned int* neighborZ,
							 unsigned int* geoD,
							 doubflo* rho,
							 doubflo* ux,
							 doubflo* uy,
							 doubflo* uz,
							 unsigned int size_Mat,
							 doubflo* DD,
							 bool EvenOrOdd);

extern "C" void InitThS7(  unsigned int numberOfThreads,
                           unsigned int* neighborX,
                           unsigned int* neighborY,
                           unsigned int* neighborZ,
                           unsigned int* geoD,
                           doubflo* Conc,
                           doubflo* ux,
                           doubflo* uy,
                           doubflo* uz,
                           unsigned int size_Mat,
                           doubflo* DD7,
                           bool EvenOrOdd);

extern "C" void InitThS27( unsigned int numberOfThreads,
                           unsigned int* neighborX,
                           unsigned int* neighborY,
                           unsigned int* neighborZ,
                           unsigned int* geoD,
                           doubflo* Conc,
                           doubflo* ux,
                           doubflo* uy,
                           doubflo* uz,
                           unsigned int size_Mat,
                           doubflo* DD27,
                           bool EvenOrOdd);

extern "C" void InitIncompAD7(   unsigned int numberOfThreads,
								 unsigned int* neighborX,
								 unsigned int* neighborY,
								 unsigned int* neighborZ,
								 unsigned int* geoD,
								 doubflo* Conc,
								 doubflo* ux,
								 doubflo* uy,
								 doubflo* uz,
								 unsigned int size_Mat,
								 doubflo* DD7,
								 bool EvenOrOdd);

extern "C" void InitIncompAD27(   unsigned int numberOfThreads,
								  unsigned int* neighborX,
								  unsigned int* neighborY,
								  unsigned int* neighborZ,
								  unsigned int* geoD,
								  doubflo* Conc,
								  doubflo* ux,
								  doubflo* uy,
								  doubflo* uz,
								  unsigned int size_Mat,
								  doubflo* DD27,
								  bool EvenOrOdd);

extern "C" void CalcMac27( doubflo* vxD,
                          doubflo* vyD,
                          doubflo* vzD,
                          doubflo* rhoD,
                          unsigned int* geoD,
                          unsigned int* neighborX,
                          unsigned int* neighborY,
                          unsigned int* neighborZ,
                          unsigned int size_Mat,
                          unsigned int grid_nx, 
                          unsigned int grid_ny, 
                          unsigned int grid_nz, 
                          doubflo* DD,
                          bool evenOrOdd);

extern "C" void CalcMacSP27(doubflo* vxD,
                            doubflo* vyD,
                            doubflo* vzD,
                            doubflo* rhoD,
                            doubflo* pressD,
                            unsigned int* geoD,
                            unsigned int* neighborX,
                            unsigned int* neighborY,
                            unsigned int* neighborZ,
                            unsigned int size_Mat,
                            unsigned int numberOfThreads, 
                            doubflo* DD,
                            bool evenOrOdd);

extern "C" void CalcMacCompSP27(doubflo* vxD,
								doubflo* vyD,
								doubflo* vzD,
								doubflo* rhoD,
								doubflo* pressD,
								unsigned int* geoD,
								unsigned int* neighborX,
								unsigned int* neighborY,
								unsigned int* neighborZ,
								unsigned int size_Mat,
								unsigned int numberOfThreads, 
								doubflo* DD,
								bool evenOrOdd);

extern "C" void CalcMacThS7(  doubflo* Conc,
                              unsigned int* geoD,
                              unsigned int* neighborX,
                              unsigned int* neighborY,
                              unsigned int* neighborZ,
                              unsigned int size_Mat,
                              unsigned int numberOfThreads, 
                              doubflo* DD7,
                              bool evenOrOdd);

extern "C" void PlaneConcThS7(doubflo* Conc,
							  int* kPC,
							  unsigned int numberOfPointskPC,
							  unsigned int* geoD,
							  unsigned int* neighborX,
							  unsigned int* neighborY,
							  unsigned int* neighborZ,
							  unsigned int size_Mat,
							  unsigned int numberOfThreads, 
							  doubflo* DD7,
							  bool evenOrOdd);

extern "C" void PlaneConcThS27(doubflo* Conc,
							   int* kPC,
							   unsigned int numberOfPointskPC,
							   unsigned int* geoD,
							   unsigned int* neighborX,
							   unsigned int* neighborY,
							   unsigned int* neighborZ,
							   unsigned int size_Mat,
							   unsigned int numberOfThreads, 
							   doubflo* DD27,
							   bool evenOrOdd);

extern "C" void CalcMacThS27( doubflo* Conc,
                              unsigned int* geoD,
                              unsigned int* neighborX,
                              unsigned int* neighborY,
                              unsigned int* neighborZ,
                              unsigned int size_Mat,
                              unsigned int numberOfThreads, 
                              doubflo* DD27,
                              bool evenOrOdd);

extern "C" void CalcMedSP27(  doubflo* vxD,
                              doubflo* vyD,
                              doubflo* vzD,
                              doubflo* rhoD,
                              doubflo* pressD,
                              unsigned int* geoD,
                              unsigned int* neighborX,
                              unsigned int* neighborY,
                              unsigned int* neighborZ,
                              unsigned int size_Mat,
                              unsigned int numberOfThreads, 
                              doubflo* DD,
                              bool evenOrOdd);

extern "C" void CalcMedCompSP27(doubflo* vxD,
								doubflo* vyD,
								doubflo* vzD,
								doubflo* rhoD,
								doubflo* pressD,
								unsigned int* geoD,
								unsigned int* neighborX,
								unsigned int* neighborY,
								unsigned int* neighborZ,
								unsigned int size_Mat,
								unsigned int numberOfThreads, 
								doubflo* DD,
								bool evenOrOdd);

extern "C" void CalcMacMedSP27(  doubflo* vxD,
                                 doubflo* vyD,
                                 doubflo* vzD,
                                 doubflo* rhoD,
                                 doubflo* pressD,
                                 unsigned int* geoD,
                                 unsigned int* neighborX,
                                 unsigned int* neighborY,
                                 unsigned int* neighborZ,
                                 unsigned int tdiff,
                                 unsigned int size_Mat,
                                 unsigned int numberOfThreads, 
                                 bool evenOrOdd);

extern "C" void Calc2ndMomentsIncompSP27(doubflo* kxyFromfcNEQ,
										 doubflo* kyzFromfcNEQ,
										 doubflo* kxzFromfcNEQ,
										 doubflo* kxxMyyFromfcNEQ,
										 doubflo* kxxMzzFromfcNEQ,
										 unsigned int* geoD,
										 unsigned int* neighborX,
										 unsigned int* neighborY,
										 unsigned int* neighborZ,
										 unsigned int size_Mat,
										 unsigned int numberOfThreads, 
										 doubflo* DD,
										 bool evenOrOdd);

extern "C" void Calc2ndMomentsCompSP27(doubflo* kxyFromfcNEQ,
									   doubflo* kyzFromfcNEQ,
									   doubflo* kxzFromfcNEQ,
									   doubflo* kxxMyyFromfcNEQ,
									   doubflo* kxxMzzFromfcNEQ,
									   unsigned int* geoD,
									   unsigned int* neighborX,
									   unsigned int* neighborY,
									   unsigned int* neighborZ,
									   unsigned int size_Mat,
									   unsigned int numberOfThreads, 
									   doubflo* DD,
									   bool evenOrOdd);

extern "C" void Calc3rdMomentsIncompSP27(doubflo* CUMbbb,
										 doubflo* CUMabc,
										 doubflo* CUMbac,
										 doubflo* CUMbca,
										 doubflo* CUMcba,
										 doubflo* CUMacb,
										 doubflo* CUMcab,
										 unsigned int* geoD,
										 unsigned int* neighborX,
										 unsigned int* neighborY,
										 unsigned int* neighborZ,
										 unsigned int size_Mat,
										 unsigned int numberOfThreads, 
										 doubflo* DD,
										 bool evenOrOdd);

extern "C" void Calc3rdMomentsCompSP27(doubflo* CUMbbb,
									   doubflo* CUMabc,
									   doubflo* CUMbac,
									   doubflo* CUMbca,
									   doubflo* CUMcba,
									   doubflo* CUMacb,
									   doubflo* CUMcab,
									   unsigned int* geoD,
									   unsigned int* neighborX,
									   unsigned int* neighborY,
									   unsigned int* neighborZ,
									   unsigned int size_Mat,
									   unsigned int numberOfThreads, 
									   doubflo* DD,
									   bool evenOrOdd);

extern "C" void CalcHigherMomentsIncompSP27(doubflo* CUMcbb,
											doubflo* CUMbcb,
											doubflo* CUMbbc,
											doubflo* CUMcca,
											doubflo* CUMcac,
											doubflo* CUMacc,
											doubflo* CUMbcc,
											doubflo* CUMcbc,
											doubflo* CUMccb,
											doubflo* CUMccc,
											unsigned int* geoD,
											unsigned int* neighborX,
											unsigned int* neighborY,
											unsigned int* neighborZ,
											unsigned int size_Mat,
											unsigned int numberOfThreads, 
											doubflo* DD,
											bool evenOrOdd);

extern "C" void CalcHigherMomentsCompSP27(doubflo* CUMcbb,
										  doubflo* CUMbcb,
										  doubflo* CUMbbc,
										  doubflo* CUMcca,
										  doubflo* CUMcac,
										  doubflo* CUMacc,
										  doubflo* CUMbcc,
										  doubflo* CUMcbc,
										  doubflo* CUMccb,
										  doubflo* CUMccc,
										  unsigned int* geoD,
										  unsigned int* neighborX,
										  unsigned int* neighborY,
										  unsigned int* neighborZ,
										  unsigned int size_Mat,
										  unsigned int numberOfThreads, 
										  doubflo* DD,
										  bool evenOrOdd);

extern "C" void LBCalcMeasurePoints27(doubflo* vxMP,
                                      doubflo* vyMP,
                                      doubflo* vzMP,
                                      doubflo* rhoMP,
                                      unsigned int* kMP,
                                      unsigned int numberOfPointskMP,
                                      unsigned int MPClockCycle,
                                      unsigned int t,
                                      unsigned int* geoD,
                                      unsigned int* neighborX,
                                      unsigned int* neighborY,
                                      unsigned int* neighborZ,
                                      unsigned int size_Mat,
                                      doubflo* DD,
                                      unsigned int numberOfThreads, 
                                      bool evenOrOdd);

extern "C" void BcPress27(int nx, 
                          int ny, 
                          int tz, 
                          unsigned int grid_nx, 
                          unsigned int grid_ny, 
                          unsigned int* bcMatD, 
                          unsigned int* neighborX,
                          unsigned int* neighborY,
                          unsigned int* neighborZ,
                          doubflo* DD, 
                          unsigned int size_Mat, 
                          bool evenOrOdd);

extern "C" void BcVel27(int nx, 
                        int ny, 
                        int nz, 
                        int itz, 
                        unsigned int grid_nx, 
                        unsigned int grid_ny, 
                        unsigned int* bcMatD, 
                        unsigned int* neighborX,
                        unsigned int* neighborY,
                        unsigned int* neighborZ,
                        doubflo* DD, 
                        unsigned int size_Mat, 
                        bool evenOrOdd, 
                        doubflo u0x, 
                        doubflo om);

extern "C" void QDev27( unsigned int numberOfThreads,
                        int nx,
                        int ny,
                        doubflo* DD, 
                        int* k_Q, 
                        doubflo* QQ,
                        unsigned int sizeQ,
                        unsigned int kQ, 
                        doubflo om1, 
                        unsigned int* neighborX,
                        unsigned int* neighborY,
                        unsigned int* neighborZ,
                        unsigned int size_Mat, 
                        bool evenOrOdd);

extern "C" void QDevComp27(unsigned int numberOfThreads,
						   int nx,
						   int ny,
						   doubflo* DD, 
						   int* k_Q, 
						   doubflo* QQ,
						   unsigned int sizeQ,
						   unsigned int kQ, 
						   doubflo om1, 
						   unsigned int* neighborX,
						   unsigned int* neighborY,
						   unsigned int* neighborZ,
						   unsigned int size_Mat, 
						   bool evenOrOdd);

extern "C" void QDev3rdMomentsComp27(  unsigned int numberOfThreads,
									   int nx,
									   int ny,
									   doubflo* DD, 
									   int* k_Q, 
									   doubflo* QQ,
									   unsigned int sizeQ,
									   unsigned int kQ, 
									   doubflo om1, 
									   unsigned int* neighborX,
									   unsigned int* neighborY,
									   unsigned int* neighborZ,
									   unsigned int size_Mat, 
									   bool evenOrOdd);

extern "C" void QDevIncompHighNu27(  unsigned int numberOfThreads,
									 int nx,
									 int ny,
									 doubflo* DD, 
									 int* k_Q, 
									 doubflo* QQ,
									 unsigned int sizeQ,
									 unsigned int kQ, 
									 doubflo om1, 
									 unsigned int* neighborX,
									 unsigned int* neighborY,
									 unsigned int* neighborZ,
									 unsigned int size_Mat, 
									 bool evenOrOdd);

extern "C" void QDevCompHighNu27(unsigned int numberOfThreads,
								 int nx,
								 int ny,
								 doubflo* DD, 
								 int* k_Q, 
								 doubflo* QQ,
								 unsigned int sizeQ,
								 unsigned int kQ, 
								 doubflo om1, 
								 unsigned int* neighborX,
								 unsigned int* neighborY,
								 unsigned int* neighborZ,
								 unsigned int size_Mat, 
								 bool evenOrOdd);

extern "C" void QVelDevicePlainBB27(unsigned int numberOfThreads,
									doubflo* vx,
									doubflo* vy,
									doubflo* vz,
									doubflo* DD,
									int* k_Q, 
									doubflo* QQ,
									unsigned int sizeQ,
									int kQ, 
									doubflo om1, 
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int size_Mat, 
									bool evenOrOdd);
	
extern "C" void QVelDeviceCouhette27(unsigned int numberOfThreads,
									doubflo* vx,
									doubflo* vy,
									doubflo* vz,
									doubflo* DD,
									int* k_Q, 
									doubflo* QQ,
									unsigned int sizeQ,
									int kQ, 
									doubflo om1, 
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int size_Mat, 
									bool evenOrOdd);

extern "C" void QVelDevice1h27( unsigned int numberOfThreads,
								int nx,
								int ny,
								doubflo* vx,
								doubflo* vy,
								doubflo* vz,
								doubflo* DD, 
								int* k_Q, 
								doubflo* QQ,
								unsigned int sizeQ,
								unsigned int kQ, 
								doubflo om1, 
								doubflo Phi, 
								doubflo angularVelocity,
								unsigned int* neighborX,
								unsigned int* neighborY,
								unsigned int* neighborZ,
								doubflo* coordX,
								doubflo* coordY,
								doubflo* coordZ,
								unsigned int size_Mat, 
								bool evenOrOdd);

extern "C" void QVelDev27(unsigned int numberOfThreads,
                          int nx,
                          int ny,
                          doubflo* vx,
                          doubflo* vy,
                          doubflo* vz,
                          doubflo* DD, 
                          int* k_Q, 
                          doubflo* QQ,
                          unsigned int sizeQ,
                          unsigned int kQ, 
                          doubflo om1, 
                          unsigned int* neighborX,
                          unsigned int* neighborY,
                          unsigned int* neighborZ,
                          unsigned int size_Mat, 
                          bool evenOrOdd);

extern "C" void QVelDevCompPlusSlip27(unsigned int numberOfThreads,
									  int nx,
									  int ny,
									  doubflo* vx,
									  doubflo* vy,
									  doubflo* vz,
									  doubflo* DD, 
									  int* k_Q, 
									  doubflo* QQ,
									  unsigned int sizeQ,
									  unsigned int kQ, 
									  doubflo om1, 
									  unsigned int* neighborX,
									  unsigned int* neighborY,
									  unsigned int* neighborZ,
									  unsigned int size_Mat, 
									  bool evenOrOdd);

extern "C" void QVelDevComp27(unsigned int numberOfThreads,
							  int nx,
							  int ny,
							  doubflo* vx,
							  doubflo* vy,
							  doubflo* vz,
							  doubflo* DD, 
							  int* k_Q, 
							  doubflo* QQ,
							  unsigned int sizeQ,
							  unsigned int kQ, 
							  doubflo om1, 
							  unsigned int* neighborX,
							  unsigned int* neighborY,
							  unsigned int* neighborZ,
							  unsigned int size_Mat, 
							  bool evenOrOdd);

extern "C" void QVelDevCompZeroPress27(unsigned int numberOfThreads,
									   int nx,
									   int ny,
									   doubflo* vx,
									   doubflo* vy,
									   doubflo* vz,
									   doubflo* DD, 
									   int* k_Q, 
									   doubflo* QQ,
									   unsigned int sizeQ,
									   int kArray, 
									   doubflo om1, 
									   unsigned int* neighborX,
									   unsigned int* neighborY,
									   unsigned int* neighborZ,
									   unsigned int size_Mat, 
									   bool evenOrOdd);

extern "C" void QVelDevIncompHighNu27(  unsigned int numberOfThreads,
										int nx,
										int ny,
										doubflo* vx,
										doubflo* vy,
										doubflo* vz,
										doubflo* DD, 
										int* k_Q, 
										doubflo* QQ,
										unsigned int sizeQ,
										unsigned int kQ, 
										doubflo om1, 
										unsigned int* neighborX,
										unsigned int* neighborY,
										unsigned int* neighborZ,
										unsigned int size_Mat, 
										bool evenOrOdd);

extern "C" void QVelDevCompHighNu27(unsigned int numberOfThreads,
									int nx,
									int ny,
									doubflo* vx,
									doubflo* vy,
									doubflo* vz,
									doubflo* DD, 
									int* k_Q, 
									doubflo* QQ,
									unsigned int sizeQ,
									unsigned int kQ, 
									doubflo om1, 
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int size_Mat, 
									bool evenOrOdd);

extern "C" void QVeloDevEQ27(unsigned int numberOfThreads,
							 doubflo* VeloX,
							 doubflo* VeloY,
							 doubflo* VeloZ,
							 doubflo* DD, 
							 int* k_Q, 
							 int kQ, 
							 doubflo om1, 
							 unsigned int* neighborX,
							 unsigned int* neighborY,
							 unsigned int* neighborZ,
							 unsigned int size_Mat, 
							 bool evenOrOdd);

extern "C" void QSlipDev27( unsigned int numberOfThreads,
							doubflo* DD, 
							int* k_Q, 
							doubflo* QQ,
							unsigned int sizeQ,
							doubflo om1, 
							unsigned int* neighborX,
							unsigned int* neighborY,
							unsigned int* neighborZ,
							unsigned int size_Mat, 
							bool evenOrOdd);

extern "C" void QSlipDevComp27(unsigned int numberOfThreads,
							   doubflo* DD, 
							   int* k_Q, 
							   doubflo* QQ,
							   unsigned int sizeQ,
							   doubflo om1, 
							   unsigned int* neighborX,
							   unsigned int* neighborY,
							   unsigned int* neighborZ,
							   unsigned int size_Mat, 
							   bool evenOrOdd);

extern "C" void QSlipGeomDevComp27( unsigned int numberOfThreads,
									doubflo* DD, 
									int* k_Q, 
									doubflo* QQ,
									unsigned int sizeQ,
									doubflo om1, 
									doubflo* NormalX,
									doubflo* NormalY,
									doubflo* NormalZ,
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int size_Mat, 
									bool evenOrOdd);

extern "C" void QSlipNormDevComp27(unsigned int numberOfThreads,
								   doubflo* DD, 
								   int* k_Q, 
								   doubflo* QQ,
								   unsigned int sizeQ,
								   doubflo om1, 
								   doubflo* NormalX,
								   doubflo* NormalY,
								   doubflo* NormalZ,
								   unsigned int* neighborX,
								   unsigned int* neighborY,
								   unsigned int* neighborZ,
								   unsigned int size_Mat, 
								   bool evenOrOdd);

extern "C" void QPressDev27(unsigned int numberOfThreads,
                          int nx,
                          int ny,
                          doubflo* rhoBC,
                          doubflo* DD, 
                          int* k_Q, 
                          doubflo* QQ,
                          unsigned int sizeQ,
                          unsigned int kQ, 
                          doubflo om1, 
                          unsigned int* neighborX,
                          unsigned int* neighborY,
                          unsigned int* neighborZ,
                          unsigned int size_Mat, 
                          bool evenOrOdd);

extern "C" void QPressDevFixBackflow27(unsigned int numberOfThreads,
                                       doubflo* rhoBC,
                                       doubflo* DD, 
                                       int* k_Q, 
                                       unsigned int kQ, 
                                       doubflo om1, 
                                       unsigned int* neighborX,
                                       unsigned int* neighborY,
                                       unsigned int* neighborZ,
                                       unsigned int size_Mat, 
                                       bool evenOrOdd);

extern "C" void QPressDevDirDepBot27(unsigned int numberOfThreads,
                                     doubflo* rhoBC,
                                     doubflo* DD, 
                                     int* k_Q, 
                                     unsigned int kQ, 
                                     doubflo om1, 
                                     unsigned int* neighborX,
                                     unsigned int* neighborY,
                                     unsigned int* neighborZ,
                                     unsigned int size_Mat, 
                                     bool evenOrOdd);

extern "C" void QPressNoRhoDev27(  unsigned int numberOfThreads,
								   doubflo* rhoBC,
								   doubflo* DD, 
								   int* k_Q, 
								   int* k_N, 
								   unsigned int kQ, 
								   doubflo om1, 
								   unsigned int* neighborX,
								   unsigned int* neighborY,
								   unsigned int* neighborZ,
								   unsigned int size_Mat, 
								   bool evenOrOdd);

extern "C" void QInflowScaleByPressDev27(unsigned int numberOfThreads,
										 doubflo* rhoBC,
										 doubflo* DD, 
										 int* k_Q, 
										 int* k_N, 
										 unsigned int kQ, 
										 doubflo om1, 
										 unsigned int* neighborX,
										 unsigned int* neighborY,
										 unsigned int* neighborZ,
										 unsigned int size_Mat, 
										 bool evenOrOdd);

extern "C" void QPressDevOld27(unsigned int numberOfThreads,
                               doubflo* rhoBC,
                               doubflo* DD, 
                               int* k_Q, 
                               int* k_N, 
                               unsigned int kQ, 
                               doubflo om1, 
                               unsigned int* neighborX,
                               unsigned int* neighborY,
                               unsigned int* neighborZ,
                               unsigned int size_Mat, 
                               bool evenOrOdd);

extern "C" void QPressDevIncompNEQ27(unsigned int numberOfThreads,
									 doubflo* rhoBC,
									 doubflo* DD, 
									 int* k_Q, 
									 int* k_N, 
									 unsigned int kQ, 
									 doubflo om1, 
									 unsigned int* neighborX,
									 unsigned int* neighborY,
									 unsigned int* neighborZ,
									 unsigned int size_Mat, 
									 bool evenOrOdd);

extern "C" void QPressDevNEQ27(unsigned int numberOfThreads,
							   doubflo* rhoBC,
							   doubflo* DD, 
							   int* k_Q, 
							   int* k_N, 
							   unsigned int kQ, 
							   doubflo om1, 
							   unsigned int* neighborX,
							   unsigned int* neighborY,
							   unsigned int* neighborZ,
							   unsigned int size_Mat, 
							   bool evenOrOdd);

extern "C" void QPressDevEQZ27(unsigned int numberOfThreads,
							   doubflo* rhoBC,
							   doubflo* DD, 
							   int* k_Q, 
							   int* k_N, 
							   doubflo* kTestRE, 
							   unsigned int kQ, 
							   doubflo om1, 
							   unsigned int* neighborX,
							   unsigned int* neighborY,
							   unsigned int* neighborZ,
							   unsigned int size_Mat, 
							   bool evenOrOdd);

extern "C" void QPressDevZero27(unsigned int numberOfThreads,
                                doubflo* DD, 
                                int* k_Q, 
                                unsigned int kQ, 
                                unsigned int* neighborX,
                                unsigned int* neighborY,
                                unsigned int* neighborZ,
                                unsigned int size_Mat, 
                                bool evenOrOdd);

extern "C" void QPressDevFake27(   unsigned int numberOfThreads,
								   doubflo* rhoBC,
								   doubflo* DD, 
								   int* k_Q, 
								   int* k_N, 
								   unsigned int kQ, 
								   doubflo om1, 
								   unsigned int* neighborX,
								   unsigned int* neighborY,
								   unsigned int* neighborZ,
								   unsigned int size_Mat, 
								   bool evenOrOdd);

extern "C" void BBDev27( unsigned int numberOfThreads,
                        int nx,
                        int ny,
                        doubflo* DD, 
                        int* k_Q, 
                        doubflo* QQ,
                        unsigned int sizeQ,
                        unsigned int kQ, 
                        doubflo om1, 
                        unsigned int* neighborX,
                        unsigned int* neighborY,
                        unsigned int* neighborZ,
                        unsigned int size_Mat, 
                        bool evenOrOdd);

extern "C" void QPressDev27_IntBB(  unsigned int numberOfThreads,
									doubflo* rho,
									doubflo* DD, 
									int* k_Q, 
									doubflo* QQ,
									unsigned int sizeQ,
									unsigned int kQ, 
									doubflo om1, 
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int size_Mat, 
									bool evenOrOdd);

extern "C" void QPressDevAntiBB27(  unsigned int numberOfThreads,
								  doubflo* rhoBC,
								  doubflo* vx,
								  doubflo* vy,
								  doubflo* vz,
								  doubflo* DD, 
								  int* k_Q, 
								  doubflo* QQ,
								  int kQ, 
								  doubflo om1, 
								  unsigned int* neighborX,
								  unsigned int* neighborY,
								  unsigned int* neighborZ,
								  unsigned int size_Mat, 
								  bool evenOrOdd);

extern "C" void PressSchlaffer27(unsigned int numberOfThreads,
                                 doubflo* rhoBC,
                                 doubflo* DD,
                                 doubflo* vx0,
                                 doubflo* vy0,
                                 doubflo* vz0,
                                 doubflo* deltaVz0,
                                 int* k_Q, 
                                 int* k_N, 
                                 int kQ, 
                                 doubflo om1, 
                                 unsigned int* neighborX,
                                 unsigned int* neighborY,
                                 unsigned int* neighborZ,
                                 unsigned int size_Mat, 
                                 bool evenOrOdd);

extern "C" void VelSchlaffer27(  unsigned int numberOfThreads,
                                 int t,
                                 doubflo* DD,
                                 doubflo* vz0,
                                 doubflo* deltaVz0,
                                 int* k_Q, 
                                 int* k_N, 
                                 int kQ, 
                                 doubflo om1, 
                                 unsigned int* neighborX,
                                 unsigned int* neighborY,
                                 unsigned int* neighborZ,
                                 unsigned int size_Mat, 
                                 bool evenOrOdd);

extern "C" void QADDev7(unsigned int numberOfThreads,
                        int nx,
                        int ny,
                        doubflo* DD, 
                        doubflo* DD7,
                        doubflo* temp,
                        doubflo diffusivity,
                        int* k_Q, 
                        doubflo* QQ,
                        unsigned int sizeQ,
                        unsigned int kQ, 
                        doubflo om1, 
                        unsigned int* neighborX,
                        unsigned int* neighborY,
                        unsigned int* neighborZ,
                        unsigned int size_Mat, 
                        bool evenOrOdd);


extern "C" void QADDirichletDev27( unsigned int numberOfThreads,
								   int nx,
								   int ny,
								   doubflo* DD, 
								   doubflo* DD27,
								   doubflo* temp,
								   doubflo diffusivity,
								   int* k_Q, 
								   doubflo* QQ,
								   unsigned int sizeQ,
								   unsigned int kQ, 
								   doubflo om1, 
								   unsigned int* neighborX,
								   unsigned int* neighborY,
								   unsigned int* neighborZ,
								   unsigned int size_Mat, 
								   bool evenOrOdd);

extern "C" void QADBBDev27(  unsigned int numberOfThreads,
							 int nx,
							 int ny,
							 doubflo* DD, 
							 doubflo* DD27,
							 doubflo* temp,
							 doubflo diffusivity,
							 int* k_Q, 
							 doubflo* QQ,
							 unsigned int sizeQ,
							 unsigned int kQ, 
							 doubflo om1, 
							 unsigned int* neighborX,
							 unsigned int* neighborY,
							 unsigned int* neighborZ,
							 unsigned int size_Mat, 
							 bool evenOrOdd);

extern "C" void QADVelDev7(unsigned int numberOfThreads,
                           int nx,
                           int ny,
                           doubflo* DD, 
                           doubflo* DD7,
                           doubflo* temp,
                           doubflo* velo,
                           doubflo diffusivity,
                           int* k_Q, 
                           doubflo* QQ,
                           unsigned int sizeQ,
                           unsigned int kQ, 
                           doubflo om1, 
                           unsigned int* neighborX,
                           unsigned int* neighborY,
                           unsigned int* neighborZ,
                           unsigned int size_Mat, 
                           bool evenOrOdd);


extern "C" void QADVelDev27(  unsigned int numberOfThreads,
                              int nx,
                              int ny,
                              doubflo* DD, 
                              doubflo* DD27,
                              doubflo* temp,
                              doubflo* velo,
                              doubflo diffusivity,
                              int* k_Q, 
                              doubflo* QQ,
                              unsigned int sizeQ,
                              unsigned int kQ, 
                              doubflo om1, 
                              unsigned int* neighborX,
                              unsigned int* neighborY,
                              unsigned int* neighborZ,
                              unsigned int size_Mat, 
                              bool evenOrOdd);

extern "C" void QADPressDev7( unsigned int numberOfThreads,
                              int nx,
                              int ny,
                              doubflo* DD, 
                              doubflo* DD7,
                              doubflo* temp,
                              doubflo* velo,
                              doubflo diffusivity,
                              int* k_Q, 
                              doubflo* QQ,
                              unsigned int sizeQ,
                              unsigned int kQ, 
                              doubflo om1, 
                              unsigned int* neighborX,
                              unsigned int* neighborY,
                              unsigned int* neighborZ,
                              unsigned int size_Mat, 
                              bool evenOrOdd);

extern "C" void QADPressDev27(unsigned int numberOfThreads,
                              int nx,
                              int ny,
                              doubflo* DD, 
                              doubflo* DD27,
                              doubflo* temp,
                              doubflo* velo,
                              doubflo diffusivity,
                              int* k_Q, 
                              doubflo* QQ,
                              unsigned int sizeQ,
                              unsigned int kQ, 
                              doubflo om1, 
                              unsigned int* neighborX,
                              unsigned int* neighborY,
                              unsigned int* neighborZ,
                              unsigned int size_Mat, 
                              bool evenOrOdd);

extern "C" void QNoSlipADincompDev7(unsigned int numberOfThreads,
									int nx,
									int ny,
									doubflo* DD, 
									doubflo* DD7,
									doubflo* temp,
									doubflo diffusivity,
									int* k_Q, 
									doubflo* QQ,
									unsigned int sizeQ,
									unsigned int kQ, 
									doubflo om1, 
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int size_Mat, 
									bool evenOrOdd);

extern "C" void QNoSlipADincompDev27(unsigned int numberOfThreads,
									 int nx,
									 int ny,
									 doubflo* DD, 
									 doubflo* DD27,
									 doubflo* temp,
									 doubflo diffusivity,
									 int* k_Q, 
									 doubflo* QQ,
									 unsigned int sizeQ,
									 unsigned int kQ, 
									 doubflo om1, 
									 unsigned int* neighborX,
									 unsigned int* neighborY,
									 unsigned int* neighborZ,
									 unsigned int size_Mat, 
									 bool evenOrOdd);

extern "C" void QADVeloIncompDev7( unsigned int numberOfThreads,
								   int nx,
								   int ny,
								   doubflo* DD, 
								   doubflo* DD7,
								   doubflo* temp,
								   doubflo* velo,
								   doubflo diffusivity,
								   int* k_Q, 
								   doubflo* QQ,
								   unsigned int sizeQ,
								   unsigned int kQ, 
								   doubflo om1, 
								   unsigned int* neighborX,
								   unsigned int* neighborY,
								   unsigned int* neighborZ,
								   unsigned int size_Mat, 
								   bool evenOrOdd);


extern "C" void QADVeloIncompDev27( unsigned int numberOfThreads,
									int nx,
									int ny,
									doubflo* DD, 
									doubflo* DD27,
									doubflo* temp,
									doubflo* velo,
									doubflo diffusivity,
									int* k_Q, 
									doubflo* QQ,
									unsigned int sizeQ,
									unsigned int kQ, 
									doubflo om1, 
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int size_Mat, 
									bool evenOrOdd);

extern "C" void QADPressIncompDev7(  unsigned int numberOfThreads,
									 int nx,
									 int ny,
									 doubflo* DD, 
									 doubflo* DD7,
									 doubflo* temp,
									 doubflo* velo,
									 doubflo diffusivity,
									 int* k_Q, 
									 doubflo* QQ,
									 unsigned int sizeQ,
									 unsigned int kQ, 
									 doubflo om1, 
									 unsigned int* neighborX,
									 unsigned int* neighborY,
									 unsigned int* neighborZ,
									 unsigned int size_Mat, 
									 bool evenOrOdd);

extern "C" void QADPressIncompDev27(  unsigned int numberOfThreads,
									  int nx,
									  int ny,
									  doubflo* DD, 
									  doubflo* DD27,
									  doubflo* temp,
									  doubflo* velo,
									  doubflo diffusivity,
									  int* k_Q, 
									  doubflo* QQ,
									  unsigned int sizeQ,
									  unsigned int kQ, 
									  doubflo om1, 
									  unsigned int* neighborX,
									  unsigned int* neighborY,
									  unsigned int* neighborZ,
									  unsigned int size_Mat, 
									  bool evenOrOdd);

extern "C" void PropVelo(   unsigned int numberOfThreads,
							unsigned int* neighborX,
							unsigned int* neighborY,
							unsigned int* neighborZ,
							doubflo* rho,
							doubflo* ux,
							doubflo* uy,
							doubflo* uz,
							int* k_Q, 
							unsigned int size_Prop,
							unsigned int size_Mat,
							unsigned int* bcMatD,
							doubflo* DD,
							bool EvenOrOdd);

extern "C" void ScaleCF27( doubflo* DC, 
                           doubflo* DF, 
                           unsigned int* neighborCX,
                           unsigned int* neighborCY,
                           unsigned int* neighborCZ,
                           unsigned int* neighborFX,
                           unsigned int* neighborFY,
                           unsigned int* neighborFZ,
                           unsigned int size_MatC, 
                           unsigned int size_MatF, 
                           bool evenOrOdd,
                           unsigned int* posCSWB, 
                           unsigned int* posFSWB, 
                           unsigned int kCF, 
                           doubflo omCoarse, 
                           doubflo omFine, 
                           doubflo nu, 
                           unsigned int nxC, 
                           unsigned int nyC, 
                           unsigned int nxF, 
                           unsigned int nyF,
                           unsigned int numberOfThreads);

extern "C" void ScaleFC27( doubflo* DC, 
                           doubflo* DF, 
                           unsigned int* neighborCX,
                           unsigned int* neighborCY,
                           unsigned int* neighborCZ,
                           unsigned int* neighborFX,
                           unsigned int* neighborFY,
                           unsigned int* neighborFZ,
                           unsigned int size_MatC, 
                           unsigned int size_MatF, 
                           bool evenOrOdd,
                           unsigned int* posC, 
                           unsigned int* posFSWB, 
                           unsigned int kFC, 
                           doubflo omCoarse, 
                           doubflo omFine, 
                           doubflo nu, 
                           unsigned int nxC, 
                           unsigned int nyC, 
                           unsigned int nxF, 
                           unsigned int nyF,
                           unsigned int numberOfThreads);

extern "C" void ScaleCFEff27(doubflo* DC, 
                             doubflo* DF, 
                             unsigned int* neighborCX,
                             unsigned int* neighborCY,
                             unsigned int* neighborCZ,
                             unsigned int* neighborFX,
                             unsigned int* neighborFY,
                             unsigned int* neighborFZ,
                             unsigned int size_MatC, 
                             unsigned int size_MatF, 
                             bool evenOrOdd,
                             unsigned int* posCSWB, 
                             unsigned int* posFSWB, 
                             unsigned int kCF, 
                             doubflo omCoarse, 
                             doubflo omFine, 
                             doubflo nu, 
                             unsigned int nxC, 
                             unsigned int nyC, 
                             unsigned int nxF, 
                             unsigned int nyF,
                             unsigned int numberOfThreads,
                             OffCF offCF);

extern "C" void ScaleFCEff27(doubflo* DC, 
                             doubflo* DF, 
                             unsigned int* neighborCX,
                             unsigned int* neighborCY,
                             unsigned int* neighborCZ,
                             unsigned int* neighborFX,
                             unsigned int* neighborFY,
                             unsigned int* neighborFZ,
                             unsigned int size_MatC, 
                             unsigned int size_MatF, 
                             bool evenOrOdd,
                             unsigned int* posC, 
                             unsigned int* posFSWB, 
                             unsigned int kFC, 
                             doubflo omCoarse, 
                             doubflo omFine, 
                             doubflo nu, 
                             unsigned int nxC, 
                             unsigned int nyC, 
                             unsigned int nxF, 
                             unsigned int nyF,
                             unsigned int numberOfThreads,
                             OffFC offFC);

extern "C" void ScaleCFLast27(doubflo* DC, 
                              doubflo* DF, 
                              unsigned int* neighborCX,
                              unsigned int* neighborCY,
                              unsigned int* neighborCZ,
                              unsigned int* neighborFX,
                              unsigned int* neighborFY,
                              unsigned int* neighborFZ,
                              unsigned int size_MatC, 
                              unsigned int size_MatF, 
                              bool evenOrOdd,
                              unsigned int* posCSWB, 
                              unsigned int* posFSWB, 
                              unsigned int kCF, 
                              doubflo omCoarse, 
                              doubflo omFine, 
                              doubflo nu, 
                              unsigned int nxC, 
                              unsigned int nyC, 
                              unsigned int nxF, 
                              unsigned int nyF,
                              unsigned int numberOfThreads,
                              OffCF offCF);

extern "C" void ScaleFCLast27(doubflo* DC, 
                              doubflo* DF, 
                              unsigned int* neighborCX,
                              unsigned int* neighborCY,
                              unsigned int* neighborCZ,
                              unsigned int* neighborFX,
                              unsigned int* neighborFY,
                              unsigned int* neighborFZ,
                              unsigned int size_MatC, 
                              unsigned int size_MatF, 
                              bool evenOrOdd,
                              unsigned int* posC, 
                              unsigned int* posFSWB, 
                              unsigned int kFC, 
                              doubflo omCoarse, 
                              doubflo omFine, 
                              doubflo nu, 
                              unsigned int nxC, 
                              unsigned int nyC, 
                              unsigned int nxF, 
                              unsigned int nyF,
                              unsigned int numberOfThreads,
                              OffFC offFC);

extern "C" void ScaleCFpress27(doubflo* DC, 
                              doubflo* DF, 
                              unsigned int* neighborCX,
                              unsigned int* neighborCY,
                              unsigned int* neighborCZ,
                              unsigned int* neighborFX,
                              unsigned int* neighborFY,
                              unsigned int* neighborFZ,
                              unsigned int size_MatC, 
                              unsigned int size_MatF, 
                              bool evenOrOdd,
                              unsigned int* posCSWB, 
                              unsigned int* posFSWB, 
                              unsigned int kCF, 
                              doubflo omCoarse, 
                              doubflo omFine, 
                              doubflo nu, 
                              unsigned int nxC, 
                              unsigned int nyC, 
                              unsigned int nxF, 
                              unsigned int nyF,
                              unsigned int numberOfThreads,
                              OffCF offCF);

extern "C" void ScaleFCpress27(  doubflo* DC, 
                                 doubflo* DF, 
                                 unsigned int* neighborCX,
                                 unsigned int* neighborCY,
                                 unsigned int* neighborCZ,
                                 unsigned int* neighborFX,
                                 unsigned int* neighborFY,
                                 unsigned int* neighborFZ,
                                 unsigned int size_MatC, 
                                 unsigned int size_MatF, 
                                 bool evenOrOdd,
                                 unsigned int* posC, 
                                 unsigned int* posFSWB, 
                                 unsigned int kFC, 
                                 doubflo omCoarse, 
                                 doubflo omFine, 
                                 doubflo nu, 
                                 unsigned int nxC, 
                                 unsigned int nyC, 
                                 unsigned int nxF, 
                                 unsigned int nyF,
                                 unsigned int numberOfThreads,
                                 OffFC offFC);

extern "C" void ScaleCF_Fix_27(doubflo* DC, 
                              doubflo* DF, 
                              unsigned int* neighborCX,
                              unsigned int* neighborCY,
                              unsigned int* neighborCZ,
                              unsigned int* neighborFX,
                              unsigned int* neighborFY,
                              unsigned int* neighborFZ,
                              unsigned int size_MatC, 
                              unsigned int size_MatF, 
                              bool evenOrOdd,
                              unsigned int* posCSWB, 
                              unsigned int* posFSWB, 
                              unsigned int kCF, 
                              doubflo omCoarse, 
                              doubflo omFine, 
                              doubflo nu, 
                              unsigned int nxC, 
                              unsigned int nyC, 
                              unsigned int nxF, 
                              unsigned int nyF,
                              unsigned int numberOfThreads,
                              OffCF offCF);

extern "C" void ScaleCF_Fix_comp_27(   doubflo* DC, 
									   doubflo* DF, 
									   unsigned int* neighborCX,
									   unsigned int* neighborCY,
									   unsigned int* neighborCZ,
									   unsigned int* neighborFX,
									   unsigned int* neighborFY,
									   unsigned int* neighborFZ,
									   unsigned int size_MatC, 
									   unsigned int size_MatF, 
									   bool evenOrOdd,
									   unsigned int* posCSWB, 
									   unsigned int* posFSWB, 
									   unsigned int kCF, 
									   doubflo omCoarse, 
									   doubflo omFine, 
									   doubflo nu, 
									   unsigned int nxC, 
									   unsigned int nyC, 
									   unsigned int nxF, 
									   unsigned int nyF,
									   unsigned int numberOfThreads,
									   OffCF offCF);

extern "C" void ScaleCF_0817_comp_27(  doubflo* DC, 
									   doubflo* DF, 
									   unsigned int* neighborCX,
									   unsigned int* neighborCY,
									   unsigned int* neighborCZ,
									   unsigned int* neighborFX,
									   unsigned int* neighborFY,
									   unsigned int* neighborFZ,
									   unsigned int size_MatC, 
									   unsigned int size_MatF, 
									   bool evenOrOdd,
									   unsigned int* posCSWB, 
									   unsigned int* posFSWB, 
									   unsigned int kCF, 
									   doubflo omCoarse, 
									   doubflo omFine, 
									   doubflo nu, 
									   unsigned int nxC, 
									   unsigned int nyC, 
									   unsigned int nxF, 
									   unsigned int nyF,
									   unsigned int numberOfThreads,
									   OffCF offCF);

extern "C" void ScaleCF_staggered_time_comp_27( doubflo* DC, 
												doubflo* DF, 
												unsigned int* neighborCX,
												unsigned int* neighborCY,
												unsigned int* neighborCZ,
												unsigned int* neighborFX,
												unsigned int* neighborFY,
												unsigned int* neighborFZ,
												unsigned int size_MatC, 
												unsigned int size_MatF, 
												bool evenOrOdd,
												unsigned int* posCSWB, 
												unsigned int* posFSWB, 
												unsigned int kCF, 
												doubflo omCoarse, 
												doubflo omFine, 
												doubflo nu, 
												unsigned int nxC, 
												unsigned int nyC, 
												unsigned int nxF, 
												unsigned int nyF,
												unsigned int numberOfThreads,
												OffCF offCF);

extern "C" void ScaleCF_RhoSq_comp_27(  doubflo* DC, 
										doubflo* DF, 
										unsigned int* neighborCX,
										unsigned int* neighborCY,
										unsigned int* neighborCZ,
										unsigned int* neighborFX,
										unsigned int* neighborFY,
										unsigned int* neighborFZ,
										unsigned int size_MatC, 
										unsigned int size_MatF, 
										bool evenOrOdd,
										unsigned int* posCSWB, 
										unsigned int* posFSWB, 
										unsigned int kCF, 
										doubflo omCoarse, 
										doubflo omFine, 
										doubflo nu, 
										unsigned int nxC, 
										unsigned int nyC, 
										unsigned int nxF, 
										unsigned int nyF,
										unsigned int numberOfThreads,
										OffCF offCF);

extern "C" void ScaleCF_RhoSq_3rdMom_comp_27( doubflo* DC, 
											  doubflo* DF, 
											  unsigned int* neighborCX,
											  unsigned int* neighborCY,
											  unsigned int* neighborCZ,
											  unsigned int* neighborFX,
											  unsigned int* neighborFY,
											  unsigned int* neighborFZ,
											  unsigned int size_MatC, 
											  unsigned int size_MatF, 
											  bool evenOrOdd,
											  unsigned int* posCSWB, 
											  unsigned int* posFSWB, 
											  unsigned int kCF, 
											  doubflo omCoarse, 
											  doubflo omFine, 
											  doubflo nu, 
											  unsigned int nxC, 
											  unsigned int nyC, 
											  unsigned int nxF, 
											  unsigned int nyF,
											  unsigned int numberOfThreads,
											  OffCF offCF);

extern "C" void ScaleCF_AA2016_comp_27( doubflo* DC, 
										doubflo* DF, 
										unsigned int* neighborCX,
										unsigned int* neighborCY,
										unsigned int* neighborCZ,
										unsigned int* neighborFX,
										unsigned int* neighborFY,
										unsigned int* neighborFZ,
										unsigned int size_MatC, 
										unsigned int size_MatF, 
										bool evenOrOdd,
										unsigned int* posCSWB, 
										unsigned int* posFSWB, 
										unsigned int kCF, 
										doubflo omCoarse, 
										doubflo omFine, 
										doubflo nu, 
										unsigned int nxC, 
										unsigned int nyC, 
										unsigned int nxF, 
										unsigned int nyF,
										unsigned int numberOfThreads,
										OffCF offCF);

extern "C" void ScaleCF_NSPress_27(doubflo* DC, 
								  doubflo* DF, 
								  unsigned int* neighborCX,
								  unsigned int* neighborCY,
								  unsigned int* neighborCZ,
								  unsigned int* neighborFX,
								  unsigned int* neighborFY,
								  unsigned int* neighborFZ,
								  unsigned int size_MatC, 
								  unsigned int size_MatF, 
								  bool evenOrOdd,
								  unsigned int* posCSWB, 
								  unsigned int* posFSWB, 
								  unsigned int kCF, 
								  doubflo omCoarse, 
								  doubflo omFine, 
								  doubflo nu, 
								  unsigned int nxC, 
								  unsigned int nyC, 
								  unsigned int nxF, 
								  unsigned int nyF,
								  unsigned int numberOfThreads,
								  OffCF offCF);

extern "C" void ScaleFC_Fix_27(  doubflo* DC, 
                                 doubflo* DF, 
                                 unsigned int* neighborCX,
                                 unsigned int* neighborCY,
                                 unsigned int* neighborCZ,
                                 unsigned int* neighborFX,
                                 unsigned int* neighborFY,
                                 unsigned int* neighborFZ,
                                 unsigned int size_MatC, 
                                 unsigned int size_MatF, 
                                 bool evenOrOdd,
                                 unsigned int* posC, 
                                 unsigned int* posFSWB, 
                                 unsigned int kFC, 
                                 doubflo omCoarse, 
                                 doubflo omFine, 
                                 doubflo nu, 
                                 unsigned int nxC, 
                                 unsigned int nyC, 
                                 unsigned int nxF, 
                                 unsigned int nyF,
                                 unsigned int numberOfThreads,
                                 OffFC offFC);

extern "C" void ScaleFC_Fix_comp_27(   doubflo* DC, 
									   doubflo* DF, 
									   unsigned int* neighborCX,
									   unsigned int* neighborCY,
									   unsigned int* neighborCZ,
									   unsigned int* neighborFX,
									   unsigned int* neighborFY,
									   unsigned int* neighborFZ,
									   unsigned int size_MatC, 
									   unsigned int size_MatF, 
									   bool evenOrOdd,
									   unsigned int* posC, 
									   unsigned int* posFSWB, 
									   unsigned int kFC, 
									   doubflo omCoarse, 
									   doubflo omFine, 
									   doubflo nu, 
									   unsigned int nxC, 
									   unsigned int nyC, 
									   unsigned int nxF, 
									   unsigned int nyF,
									   unsigned int numberOfThreads,
									   OffFC offFC);

extern "C" void ScaleFC_0817_comp_27(  doubflo* DC, 
									   doubflo* DF, 
									   unsigned int* neighborCX,
									   unsigned int* neighborCY,
									   unsigned int* neighborCZ,
									   unsigned int* neighborFX,
									   unsigned int* neighborFY,
									   unsigned int* neighborFZ,
									   unsigned int size_MatC, 
									   unsigned int size_MatF, 
									   bool evenOrOdd,
									   unsigned int* posC, 
									   unsigned int* posFSWB, 
									   unsigned int kFC, 
									   doubflo omCoarse, 
									   doubflo omFine, 
									   doubflo nu, 
									   unsigned int nxC, 
									   unsigned int nyC, 
									   unsigned int nxF, 
									   unsigned int nyF,
									   unsigned int numberOfThreads,
									   OffFC offFC);

extern "C" void ScaleFC_staggered_time_comp_27( doubflo* DC, 
												doubflo* DF, 
												unsigned int* neighborCX,
												unsigned int* neighborCY,
												unsigned int* neighborCZ,
												unsigned int* neighborFX,
												unsigned int* neighborFY,
												unsigned int* neighborFZ,
												unsigned int size_MatC, 
												unsigned int size_MatF, 
												bool evenOrOdd,
												unsigned int* posC, 
												unsigned int* posFSWB, 
												unsigned int kFC, 
												doubflo omCoarse, 
												doubflo omFine, 
												doubflo nu, 
												unsigned int nxC, 
												unsigned int nyC, 
												unsigned int nxF, 
												unsigned int nyF,
												unsigned int numberOfThreads,
												OffFC offFC);

extern "C" void ScaleFC_RhoSq_comp_27(  doubflo* DC, 
										doubflo* DF, 
										unsigned int* neighborCX,
										unsigned int* neighborCY,
										unsigned int* neighborCZ,
										unsigned int* neighborFX,
										unsigned int* neighborFY,
										unsigned int* neighborFZ,
										unsigned int size_MatC, 
										unsigned int size_MatF, 
										bool evenOrOdd,
										unsigned int* posC, 
										unsigned int* posFSWB, 
										unsigned int kFC, 
										doubflo omCoarse, 
										doubflo omFine, 
										doubflo nu, 
										unsigned int nxC, 
										unsigned int nyC, 
										unsigned int nxF, 
										unsigned int nyF,
										unsigned int numberOfThreads,
										OffFC offFC);

extern "C" void ScaleFC_RhoSq_3rdMom_comp_27( doubflo* DC, 
											  doubflo* DF, 
											  unsigned int* neighborCX,
											  unsigned int* neighborCY,
											  unsigned int* neighborCZ,
											  unsigned int* neighborFX,
											  unsigned int* neighborFY,
											  unsigned int* neighborFZ,
											  unsigned int size_MatC, 
											  unsigned int size_MatF, 
											  bool evenOrOdd,
											  unsigned int* posC, 
											  unsigned int* posFSWB, 
											  unsigned int kFC, 
											  doubflo omCoarse, 
											  doubflo omFine, 
											  doubflo nu, 
											  unsigned int nxC, 
											  unsigned int nyC, 
											  unsigned int nxF, 
											  unsigned int nyF,
											  unsigned int numberOfThreads,
											  OffFC offFC);

extern "C" void ScaleFC_AA2016_comp_27( doubflo* DC, 
										doubflo* DF, 
										unsigned int* neighborCX,
										unsigned int* neighborCY,
										unsigned int* neighborCZ,
										unsigned int* neighborFX,
										unsigned int* neighborFY,
										unsigned int* neighborFZ,
										unsigned int size_MatC, 
										unsigned int size_MatF, 
										bool evenOrOdd,
										unsigned int* posC, 
										unsigned int* posFSWB, 
										unsigned int kFC, 
										doubflo omCoarse, 
										doubflo omFine, 
										doubflo nu, 
										unsigned int nxC, 
										unsigned int nyC, 
										unsigned int nxF, 
										unsigned int nyF,
										unsigned int numberOfThreads,
										OffFC offFC);

extern "C" void ScaleFC_NSPress_27(  doubflo* DC, 
									 doubflo* DF, 
									 unsigned int* neighborCX,
									 unsigned int* neighborCY,
									 unsigned int* neighborCZ,
									 unsigned int* neighborFX,
									 unsigned int* neighborFY,
									 unsigned int* neighborFZ,
									 unsigned int size_MatC, 
									 unsigned int size_MatF, 
									 bool evenOrOdd,
									 unsigned int* posC, 
									 unsigned int* posFSWB, 
									 unsigned int kFC, 
									 doubflo omCoarse, 
									 doubflo omFine, 
									 doubflo nu, 
									 unsigned int nxC, 
									 unsigned int nyC, 
									 unsigned int nxF, 
									 unsigned int nyF,
									 unsigned int numberOfThreads,
									 OffFC offFC);

extern "C" void ScaleCFThS7(  doubflo* DC, 
                              doubflo* DF, 
                              doubflo* DD7C, 
                              doubflo* DD7F,
                              unsigned int* neighborCX,
                              unsigned int* neighborCY,
                              unsigned int* neighborCZ,
                              unsigned int* neighborFX,
                              unsigned int* neighborFY,
                              unsigned int* neighborFZ,
                              unsigned int size_MatC, 
                              unsigned int size_MatF, 
                              bool evenOrOdd,
                              unsigned int* posCSWB, 
                              unsigned int* posFSWB, 
                              unsigned int kCF, 
                              doubflo nu,
                              doubflo diffusivity_fine,
                              unsigned int numberOfThreads);

extern "C" void ScaleFCThS7(  doubflo* DC, 
                              doubflo* DF,
                              doubflo* DD7C, 
                              doubflo* DD7F,
                              unsigned int* neighborCX,
                              unsigned int* neighborCY,
                              unsigned int* neighborCZ,
                              unsigned int* neighborFX,
                              unsigned int* neighborFY,
                              unsigned int* neighborFZ,
                              unsigned int size_MatC, 
                              unsigned int size_MatF, 
                              bool evenOrOdd,
                              unsigned int* posC, 
                              unsigned int* posFSWB, 
                              unsigned int kFC, 
                              doubflo nu,
                              doubflo diffusivity_coarse,
                              unsigned int numberOfThreads);

extern "C" void ScaleCFThSMG7(   doubflo* DC, 
                                 doubflo* DF,
                                 doubflo* DD7C, 
                                 doubflo* DD7F,
                                 unsigned int* neighborCX,
                                 unsigned int* neighborCY,
                                 unsigned int* neighborCZ,
                                 unsigned int* neighborFX,
                                 unsigned int* neighborFY,
                                 unsigned int* neighborFZ,
                                 unsigned int size_MatC, 
                                 unsigned int size_MatF, 
                                 bool evenOrOdd,
                                 unsigned int* posCSWB, 
                                 unsigned int* posFSWB, 
                                 unsigned int kCF, 
                                 doubflo nu,
                                 doubflo diffusivity_fine,
                                 unsigned int numberOfThreads,
                                 OffCF offCF);

extern "C" void ScaleFCThSMG7(doubflo* DC, 
                              doubflo* DF,
                              doubflo* DD7C, 
                              doubflo* DD7F,
                              unsigned int* neighborCX,
                              unsigned int* neighborCY,
                              unsigned int* neighborCZ,
                              unsigned int* neighborFX,
                              unsigned int* neighborFY,
                              unsigned int* neighborFZ,
                              unsigned int size_MatC, 
                              unsigned int size_MatF, 
                              bool evenOrOdd,
                              unsigned int* posC, 
                              unsigned int* posFSWB, 
                              unsigned int kFC, 
                              doubflo nu,
                              doubflo diffusivity_coarse,
                              unsigned int numberOfThreads,
                              OffFC offFC);

extern "C" void ScaleCFThS27( doubflo* DC, 
                              doubflo* DF, 
                              doubflo* DD27C, 
                              doubflo* DD27F,
                              unsigned int* neighborCX,
                              unsigned int* neighborCY,
                              unsigned int* neighborCZ,
                              unsigned int* neighborFX,
                              unsigned int* neighborFY,
                              unsigned int* neighborFZ,
                              unsigned int size_MatC, 
                              unsigned int size_MatF, 
                              bool evenOrOdd,
                              unsigned int* posCSWB, 
                              unsigned int* posFSWB, 
                              unsigned int kCF, 
                              doubflo nu,
                              doubflo diffusivity_fine,
							  unsigned int numberOfThreads,
							  OffCF offCF);

extern "C" void ScaleFCThS27( doubflo* DC, 
                              doubflo* DF,
                              doubflo* DD27C, 
                              doubflo* DD27F,
                              unsigned int* neighborCX,
                              unsigned int* neighborCY,
                              unsigned int* neighborCZ,
                              unsigned int* neighborFX,
                              unsigned int* neighborFY,
                              unsigned int* neighborFZ,
                              unsigned int size_MatC, 
                              unsigned int size_MatF, 
                              bool evenOrOdd,
                              unsigned int* posC, 
                              unsigned int* posFSWB, 
                              unsigned int kFC, 
                              doubflo nu,
                              doubflo diffusivity_coarse,
							  unsigned int numberOfThreads,
							  OffFC offFC);

extern "C" void DragLiftPostD27(doubflo* DD, 
								int* k_Q, 
								doubflo* QQ,
								int kQ, 
								double *DragX,
								double *DragY,
								double *DragZ,
								unsigned int* neighborX,
								unsigned int* neighborY,
								unsigned int* neighborZ,
								unsigned int size_Mat, 
								bool evenOrOdd,
								unsigned int numberOfThreads);

extern "C" void DragLiftPreD27( doubflo* DD, 
								int* k_Q, 
								doubflo* QQ,
								int kQ, 
								double *DragX,
								double *DragY,
								double *DragZ,
								unsigned int* neighborX,
								unsigned int* neighborY,
								unsigned int* neighborZ,
								unsigned int size_Mat, 
								bool evenOrOdd,
								unsigned int numberOfThreads);

extern "C" void CalcCPtop27(doubflo* DD, 
							int* cpIndex, 
							int nonCp, 
							double *cpPress,
							unsigned int* neighborX,
							unsigned int* neighborY,
							unsigned int* neighborZ,
							unsigned int size_Mat, 
							bool evenOrOdd,
							unsigned int numberOfThreads);

extern "C" void CalcCPbottom27(doubflo* DD, 
							   int* cpIndex, 
							   int nonCp, 
							   double *cpPress,
							   unsigned int* neighborX,
							   unsigned int* neighborY,
							   unsigned int* neighborZ,
							   unsigned int size_Mat, 
							   bool evenOrOdd,
							   unsigned int numberOfThreads);

extern "C" void GetSendFsPreDev27(doubflo* DD,
								  doubflo* bufferFs,
								  int* sendIndex,
								  int buffmax,
								  unsigned int* neighborX,
								  unsigned int* neighborY,
								  unsigned int* neighborZ,
								  unsigned int size_Mat, 
								  bool evenOrOdd,
								  unsigned int numberOfThreads);

extern "C" void GetSendFsPostDev27(doubflo* DD,
								   doubflo* bufferFs,
								   int* sendIndex,
								   int buffmax,
								   unsigned int* neighborX,
								   unsigned int* neighborY,
								   unsigned int* neighborZ,
								   unsigned int size_Mat, 
								   bool evenOrOdd,
								   unsigned int numberOfThreads);

extern "C" void SetRecvFsPreDev27(doubflo* DD,
								  doubflo* bufferFs,
								  int* recvIndex,
								  int buffmax,
								  unsigned int* neighborX,
								  unsigned int* neighborY,
								  unsigned int* neighborZ,
								  unsigned int size_Mat, 
								  bool evenOrOdd,
								  unsigned int numberOfThreads);

extern "C" void SetRecvFsPostDev27(doubflo* DD,
								   doubflo* bufferFs,
								   int* recvIndex,
								   int buffmax,
								   unsigned int* neighborX,
								   unsigned int* neighborY,
								   unsigned int* neighborZ,
								   unsigned int size_Mat, 
								   bool evenOrOdd,
								   unsigned int numberOfThreads);

extern "C" void WallFuncDev27(unsigned int numberOfThreads,
							  int nx,
							  int ny,
							  doubflo* vx,
							  doubflo* vy,
							  doubflo* vz,
							  doubflo* DD, 
							  int* k_Q, 
							  doubflo* QQ,
							  unsigned int sizeQ,
							  unsigned int kQ, 
							  doubflo om1, 
							  unsigned int* neighborX,
							  unsigned int* neighborY,
							  unsigned int* neighborZ,
							  unsigned int size_Mat, 
							  bool evenOrOdd);

extern "C" void SetOutputWallVelocitySP27(unsigned int numberOfThreads,
										  doubflo* vxD,
										  doubflo* vyD,
										  doubflo* vzD,
										  doubflo* vxWall,
										  doubflo* vyWall,
										  doubflo* vzWall,
										  int numberOfWallNodes, 
										  int* kWallNodes, 
										  doubflo* rhoD,
										  doubflo* pressD,
										  unsigned int* geoD,
										  unsigned int* neighborX,
										  unsigned int* neighborY,
										  unsigned int* neighborZ,
										  unsigned int size_Mat,
										  doubflo* DD,
										  bool evenOrOdd);

extern "C" void GetVelotoForce27(unsigned int numberOfThreads,
								 doubflo* DD, 
								 int* bcIndex, 
								 int nonAtBC, 
								 doubflo* Vx,
								 doubflo* Vy,
								 doubflo* Vz,
								 unsigned int* neighborX,
								 unsigned int* neighborY,
								 unsigned int* neighborZ,
								 unsigned int size_Mat, 
								 bool evenOrOdd);

extern "C" void InitParticlesDevice(doubflo* coordX,
									doubflo* coordY,
									doubflo* coordZ, 
									doubflo* coordParticleXlocal,
									doubflo* coordParticleYlocal,
									doubflo* coordParticleZlocal, 
									doubflo* coordParticleXglobal,
									doubflo* coordParticleYglobal,
									doubflo* coordParticleZglobal,
									doubflo* veloParticleX,
									doubflo* veloParticleY,
									doubflo* veloParticleZ,
									doubflo* randArray,
									unsigned int* particleID,
									unsigned int* cellBaseID,
									unsigned int* bcMatD,
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int* neighborWSB,
									int level,
									unsigned int numberOfParticles, 
									unsigned int size_Mat,
									unsigned int numberOfThreads);

extern "C" void MoveParticlesDevice(doubflo* coordX,
									doubflo* coordY,
									doubflo* coordZ, 
									doubflo* coordParticleXlocal,
									doubflo* coordParticleYlocal,
									doubflo* coordParticleZlocal, 
									doubflo* coordParticleXglobal,
									doubflo* coordParticleYglobal,
									doubflo* coordParticleZglobal,
									doubflo* veloParticleX,
									doubflo* veloParticleY,
									doubflo* veloParticleZ,
									doubflo* DD,
									doubflo  omega,
									unsigned int* particleID,
									unsigned int* cellBaseID,
									unsigned int* bcMatD,
									unsigned int* neighborX,
									unsigned int* neighborY,
									unsigned int* neighborZ,
									unsigned int* neighborWSB,
									int level,
									unsigned int timestep, 
									unsigned int numberOfTimesteps, 
									unsigned int numberOfParticles, 
									unsigned int size_Mat,
									unsigned int numberOfThreads,
									bool evenOrOdd);

extern "C" void initRandomDevice(curandState* state,
								 unsigned int size_Mat,
								 unsigned int numberOfThreads);

extern "C" void generateRandomValuesDevice(curandState* state,
										   unsigned int size_Mat,
										   doubflo* randArray,
										   unsigned int numberOfThreads);

