include(${VF_CMAKE_DIR}/3rd/boost.cmake)
include(${VF_CMAKE_DIR}/3rd/cuda.cmake)
include(${VF_CMAKE_DIR}/3rd/gmock.cmake)
include(${VF_CMAKE_DIR}/3rd/mpi.cmake)
include(${VF_CMAKE_DIR}/3rd/OpenMP.cmake)